// @generated by protoc-gen-es-starpc none with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/s4wave/spacewave/sdk/chat/rpc/rpc.proto (package spacewave.chat.rpc, syntax proto3)
/* eslint-disable */

import {
  GetChannelInfoRequest,
  GetChannelInfoResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  SendMessageRequest,
  SendMessageResponse,
  WatchMessagesRequest,
  WatchMessagesResponse,
} from './rpc.pb.js'
import { MethodKind } from '@aptre/protobuf-es-lite'
import {
  buildDecodeMessageTransform,
  MessageStream,
  ProtoRpc,
  ServerContext,
} from 'starpc'

/**
 * ChatResourceService serves authorized operations for one chat channel.
 *
 * @generated from service spacewave.chat.rpc.ChatResourceService
 */
export const ChatResourceServiceDefinition = {
  typeName: 'spacewave.chat.rpc.ChatResourceService',
  methods: {
    /**
     * GetChannelInfo returns channel metadata and its retained history extent.
     *
     * @generated from rpc spacewave.chat.rpc.ChatResourceService.GetChannelInfo
     */
    GetChannelInfo: {
      name: 'GetChannelInfo',
      I: GetChannelInfoRequest,
      O: GetChannelInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListMessages returns a bounded page of channel history.
     *
     * @generated from rpc spacewave.chat.rpc.ChatResourceService.ListMessages
     */
    ListMessages: {
      name: 'ListMessages',
      I: ListMessagesRequest,
      O: ListMessagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * WatchMessages streams channel messages after each shared-state change.
     *
     * @generated from rpc spacewave.chat.rpc.ChatResourceService.WatchMessages
     */
    WatchMessages: {
      name: 'WatchMessages',
      I: WatchMessagesRequest,
      O: WatchMessagesResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * SendMessage appends one message or resolves an identical retry.
     *
     * @generated from rpc spacewave.chat.rpc.ChatResourceService.SendMessage
     */
    SendMessage: {
      name: 'SendMessage',
      I: SendMessageRequest,
      O: SendMessageResponse,
      kind: MethodKind.Unary,
    },
  },
} as const

/**
 * ChatResourceService serves authorized operations for one chat channel.
 *
 * @generated from service spacewave.chat.rpc.ChatResourceService
 */
export interface ChatResourceService {
  /**
   * GetChannelInfo returns channel metadata and its retained history extent.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.GetChannelInfo
   */
  GetChannelInfo(
    request: GetChannelInfoRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetChannelInfoResponse>

  /**
   * ListMessages returns a bounded page of channel history.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.ListMessages
   */
  ListMessages(
    request: ListMessagesRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListMessagesResponse>

  /**
   * WatchMessages streams channel messages after each shared-state change.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.WatchMessages
   */
  WatchMessages(
    request: WatchMessagesRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchMessagesResponse>

  /**
   * SendMessage appends one message or resolves an identical retry.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.SendMessage
   */
  SendMessage(
    request: SendMessageRequest,
    abortSignal?: AbortSignal,
  ): Promise<SendMessageResponse>
}

/**
 * ChatResourceService serves authorized operations for one chat channel.
 *
 * @generated from service spacewave.chat.rpc.ChatResourceService
 */
export interface ChatResourceServiceHandler {
  /**
   * GetChannelInfo returns channel metadata and its retained history extent.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.GetChannelInfo
   */
  GetChannelInfo(
    request: GetChannelInfoRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<GetChannelInfoResponse>

  /**
   * ListMessages returns a bounded page of channel history.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.ListMessages
   */
  ListMessages(
    request: ListMessagesRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ListMessagesResponse>

  /**
   * WatchMessages streams channel messages after each shared-state change.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.WatchMessages
   */
  WatchMessages(
    request: WatchMessagesRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchMessagesResponse>

  /**
   * SendMessage appends one message or resolves an identical retry.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.SendMessage
   */
  SendMessage(
    request: SendMessageRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<SendMessageResponse>
}

export const ChatResourceServiceServiceName =
  ChatResourceServiceDefinition.typeName

export class ChatResourceServiceClient implements ChatResourceService {
  private readonly rpc: ProtoRpc
  private readonly service: string
  constructor(rpc: ProtoRpc, opts?: { service?: string }) {
    this.service = opts?.service || ChatResourceServiceServiceName
    this.rpc = rpc
    this.GetChannelInfo = this.GetChannelInfo.bind(this)
    this.ListMessages = this.ListMessages.bind(this)
    this.WatchMessages = this.WatchMessages.bind(this)
    this.SendMessage = this.SendMessage.bind(this)
  }
  /**
   * GetChannelInfo returns channel metadata and its retained history extent.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.GetChannelInfo
   */
  async GetChannelInfo(
    request: GetChannelInfoRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetChannelInfoResponse> {
    const requestMsg = GetChannelInfoRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      ChatResourceServiceDefinition.methods.GetChannelInfo.name,
      GetChannelInfoRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return GetChannelInfoResponse.fromBinary(result)
  }

  /**
   * ListMessages returns a bounded page of channel history.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.ListMessages
   */
  async ListMessages(
    request: ListMessagesRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListMessagesResponse> {
    const requestMsg = ListMessagesRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      ChatResourceServiceDefinition.methods.ListMessages.name,
      ListMessagesRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ListMessagesResponse.fromBinary(result)
  }

  /**
   * WatchMessages streams channel messages after each shared-state change.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.WatchMessages
   */
  WatchMessages(
    request: WatchMessagesRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchMessagesResponse> {
    const requestMsg = WatchMessagesRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      ChatResourceServiceDefinition.methods.WatchMessages.name,
      WatchMessagesRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchMessagesResponse)(result)
  }

  /**
   * SendMessage appends one message or resolves an identical retry.
   *
   * @generated from rpc spacewave.chat.rpc.ChatResourceService.SendMessage
   */
  async SendMessage(
    request: SendMessageRequest,
    abortSignal?: AbortSignal,
  ): Promise<SendMessageResponse> {
    const requestMsg = SendMessageRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      ChatResourceServiceDefinition.methods.SendMessage.name,
      SendMessageRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return SendMessageResponse.fromBinary(result)
  }
}
