// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.18.1-0.20260826222423-298dca0e6eaf
// source: github.com/s4wave/spacewave/core/sync/node/node.proto

package core_sync_node

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

// Kind identifies the required Worker lifecycle operation or response.
type RuntimeMessage_Kind int32

const (
	// KIND_UNKNOWN is invalid for every lifecycle operation.
	RuntimeMessage_KIND_UNKNOWN RuntimeMessage_Kind = 0
	// READY confirms the World is open and accepts Resource streams.
	RuntimeMessage_READY RuntimeMessage_Kind = 1
	// OPEN_STREAM supplies one transferred MessagePort for a StaRPC exchange.
	RuntimeMessage_OPEN_STREAM RuntimeMessage_Kind = 2
	// CLOSE stops admission and requests a durable, joined shutdown.
	RuntimeMessage_CLOSE RuntimeMessage_Kind = 3
	// CLOSED reports completion of shutdown, including any failure.
	RuntimeMessage_CLOSED RuntimeMessage_Kind = 4
	// FAILED reports a startup or protocol failure before orderly shutdown.
	RuntimeMessage_FAILED RuntimeMessage_Kind = 5
)

// Enum value maps for RuntimeMessage_Kind.
var (
	RuntimeMessage_Kind_name = map[int32]string{
		0: "KIND_UNKNOWN",
		1: "READY",
		2: "OPEN_STREAM",
		3: "CLOSE",
		4: "CLOSED",
		5: "FAILED",
	}
	RuntimeMessage_Kind_value = map[string]int32{
		"KIND_UNKNOWN": 0,
		"READY":        1,
		"OPEN_STREAM":  2,
		"CLOSE":        3,
		"CLOSED":       4,
		"FAILED":       5,
	}
)

func (x RuntimeMessage_Kind) Enum() *RuntimeMessage_Kind {
	p := new(RuntimeMessage_Kind)
	*p = x
	return p
}

func (x RuntimeMessage_Kind) String() string {
	name, valid := RuntimeMessage_Kind_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// RuntimeInit selects the exclusively owned storage directory for one Worker.
type RuntimeInit struct {
	unknownFields []byte
	// Directory is the filesystem path exclusively owned until the Worker exits.
	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *RuntimeInit) Reset() {
	*x = RuntimeInit{}
}

func (*RuntimeInit) ProtoMessage() {}

func (x *RuntimeInit) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

// RuntimeMessage controls the Worker lifetime outside its Resource connection.
// OPEN_STREAM accompanies a transferred MessagePort carrying StaRPC packets.
type RuntimeMessage struct {
	unknownFields []byte
	// Kind selects the required operation or response.
	Kind RuntimeMessage_Kind `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Error describes a failure in FAILED or CLOSED and is empty on success.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RuntimeMessage) Reset() {
	*x = RuntimeMessage{}
}

func (*RuntimeMessage) ProtoMessage() {}

func (x *RuntimeMessage) GetKind() RuntimeMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return RuntimeMessage_KIND_UNKNOWN
}

func (x *RuntimeMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (m *RuntimeInit) CloneVT() *RuntimeInit {
	if m == nil {
		return (*RuntimeInit)(nil)
	}
	r := new(RuntimeInit)
	r.Directory = m.Directory
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *RuntimeInit) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *RuntimeMessage) CloneVT() *RuntimeMessage {
	if m == nil {
		return (*RuntimeMessage)(nil)
	}
	r := new(RuntimeMessage)
	r.Kind = m.Kind
	r.Error = m.Error
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *RuntimeMessage) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *RuntimeInit) EqualVT(that *RuntimeInit) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Directory != that.Directory {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RuntimeInit) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*RuntimeInit)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *RuntimeMessage) EqualVT(that *RuntimeMessage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Kind != that.Kind {
		return false
	}
	if this.Error != that.Error {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RuntimeMessage) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*RuntimeMessage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the RuntimeInit message to JSON.
func (x *RuntimeInit) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Directory != "" || s.HasField("directory") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("directory")
		s.WriteString(x.Directory)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the RuntimeInit to JSON.
func (x *RuntimeInit) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the RuntimeInit message from JSON.
func (x *RuntimeInit) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "directory":
			s.AddField("directory")
			x.Directory = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the RuntimeInit from JSON.
func (x *RuntimeInit) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the RuntimeMessage_Kind to JSON.
func (x RuntimeMessage_Kind) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), RuntimeMessage_Kind_name)
}

// MarshalText marshals the RuntimeMessage_Kind to text.
func (x RuntimeMessage_Kind) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), RuntimeMessage_Kind_name)), nil
}

// MarshalJSON marshals the RuntimeMessage_Kind to JSON.
func (x RuntimeMessage_Kind) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the RuntimeMessage_Kind from JSON.
func (x *RuntimeMessage_Kind) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(RuntimeMessage_Kind_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read Kind enum: %v", err)
		return
	}
	*x = RuntimeMessage_Kind(v)
}

// UnmarshalText unmarshals the RuntimeMessage_Kind from text.
func (x *RuntimeMessage_Kind) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), RuntimeMessage_Kind_value)
	if err != nil {
		return err
	}
	*x = RuntimeMessage_Kind(i)
	return nil
}

// UnmarshalJSON unmarshals the RuntimeMessage_Kind from JSON.
func (x *RuntimeMessage_Kind) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the RuntimeMessage message to JSON.
func (x *RuntimeMessage) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Kind != 0 || s.HasField("kind") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("kind")
		x.Kind.MarshalProtoJSON(s)
	}
	if x.Error != "" || s.HasField("error") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("error")
		s.WriteString(x.Error)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the RuntimeMessage to JSON.
func (x *RuntimeMessage) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the RuntimeMessage message from JSON.
func (x *RuntimeMessage) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "kind":
			s.AddField("kind")
			x.Kind.UnmarshalProtoJSON(s)
		case "error":
			s.AddField("error")
			x.Error = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the RuntimeMessage from JSON.
func (x *RuntimeMessage) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *RuntimeInit) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RuntimeInit) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *RuntimeInit) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Directory) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Directory)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RuntimeMessage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RuntimeMessage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *RuntimeMessage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Error) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Error)
		i--
		dAtA[i] = 0x12
	}
	if m.Kind != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RuntimeInit) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Directory)
	n += len(m.unknownFields)
	return n
}

func (m *RuntimeMessage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Kind)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Error)
	n += len(m.unknownFields)
	return n
}

func (x *RuntimeInit) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "RuntimeInit")
	if x.Directory != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "directory")
		protobuf_go_lite.TextWriteString(&sb, x.Directory)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *RuntimeInit) String() string {
	return x.MarshalProtoText()
}

func (x RuntimeMessage_Kind) MarshalProtoText() string {
	return x.String()
}

func (x *RuntimeMessage) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "RuntimeMessage")
	if x.Kind != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "kind")
		protobuf_go_lite.TextWriteStringer(&sb, RuntimeMessage_Kind(x.Kind))
	}
	if x.Error != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error")
		protobuf_go_lite.TextWriteString(&sb, x.Error)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *RuntimeMessage) String() string {
	return x.MarshalProtoText()
}

func (m *RuntimeInit) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RuntimeInit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RuntimeInit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Directory", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Directory = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RuntimeMessage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RuntimeMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RuntimeMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.Kind = RuntimeMessage_Kind(_v)
			if err != nil {
				return err
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Error = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
