// @generated
// This file is @generated by prost-build.
/// StreamEstablish is the first message sent by the initiator of a stream.
/// Prefixed by a uint32 length.
/// Max size: 100kb
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamEstablish {
    /// ProtocolID is the protocol identifier string for the stream.
    #[prost(string, tag="1")]
    pub protocol_id: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
