// @generated
// This file is @generated by prost-build.
/// Signature contains a signature by a peer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Signature {
    /// PubKey is the public key of the peer.
    /// May be empty if the public key is to be inferred from context.
    #[prost(bytes="vec", tag="1")]
    pub pub_key: ::prost::alloc::vec::Vec<u8>,
    /// HashType is the hash type used to hash the data.
    /// The signature is then of the hash bytes (usually 32).
    #[prost(enumeration="super::hash::HashType", tag="2")]
    pub hash_type: i32,
    /// SigData contains the signature data.
    /// The format is defined by the key type.
    #[prost(bytes="vec", tag="3")]
    pub sig_data: ::prost::alloc::vec::Vec<u8>,
}
/// SignedMsg is a message from a peer with a signature.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedMsg {
    /// FromPeerId is the peer identifier of the sender.
    #[prost(string, tag="1")]
    pub from_peer_id: ::prost::alloc::string::String,
    /// Signature is the sender signature.
    /// Should not contain PubKey, which is inferred from peer id.
    #[prost(message, optional, tag="2")]
    pub signature: ::core::option::Option<Signature>,
    /// Data is the signed data.
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
