// Code generated by protoc-gen-srpc. DO NOT EDIT.
// protoc-gen-srpc version: v0.52.1
// source: github.com/s4wave/spacewave/sdk/space/space.proto

package s4wave_space

import (
	context "context"

	srpc "github.com/aperturerobotics/starpc/srpc"
	s4wave_deploy "github.com/s4wave/spacewave/sdk/deploy"
)

type SRPCSpaceResourceServiceClient interface {
	// SRPCClient returns the underlying SRPC client.
	SRPCClient() srpc.Client

	WatchSpaceState(ctx context.Context, in *WatchSpaceStateRequest) (SRPCSpaceResourceService_WatchSpaceStateClient, error)

	WatchSpaceSharingState(ctx context.Context, in *WatchSpaceSharingStateRequest) (SRPCSpaceResourceService_WatchSpaceSharingStateClient, error)

	AccessWorld(ctx context.Context, in *AccessWorldRequest) (*AccessWorldResponse, error)

	MountSpaceContents(ctx context.Context, in *MountSpaceContentsRequest) (*MountSpaceContentsResponse, error)

	CreateSecret(ctx context.Context, in *CreateSecretRequest) (*CreateSecretResponse, error)

	ReadSecretPayload(ctx context.Context, in *ReadSecretPayloadRequest) (*ReadSecretPayloadResponse, error)

	DeployManifests(ctx context.Context) (SRPCSpaceResourceService_DeployManifestsClient, error)

	AddSpacePlugin(ctx context.Context, in *AddSpacePluginRequest) (*AddSpacePluginResponse, error)

	RemoveSpacePlugin(ctx context.Context, in *RemoveSpacePluginRequest) (*RemoveSpacePluginResponse, error)
}

type srpcSpaceResourceServiceClient struct {
	cc        srpc.Client
	serviceID string
}

func NewSRPCSpaceResourceServiceClient(cc srpc.Client) SRPCSpaceResourceServiceClient {
	return &srpcSpaceResourceServiceClient{cc: cc, serviceID: SRPCSpaceResourceServiceServiceID}
}

func NewSRPCSpaceResourceServiceClientWithServiceID(cc srpc.Client, serviceID string) SRPCSpaceResourceServiceClient {
	if serviceID == "" {
		serviceID = SRPCSpaceResourceServiceServiceID
	}
	return &srpcSpaceResourceServiceClient{cc: cc, serviceID: serviceID}
}

func (c *srpcSpaceResourceServiceClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcSpaceResourceServiceClient) WatchSpaceState(ctx context.Context, in *WatchSpaceStateRequest) (SRPCSpaceResourceService_WatchSpaceStateClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "WatchSpaceState", in)
	if err != nil {
		return nil, err
	}
	strm := &srpcSpaceResourceService_WatchSpaceStateClient{stream}
	if err := strm.CloseSend(); err != nil {
		return nil, err
	}
	return strm, nil
}

type SRPCSpaceResourceService_WatchSpaceStateClient interface {
	srpc.Stream
	Recv() (*SpaceState, error)
	RecvTo(*SpaceState) error
}

type srpcSpaceResourceService_WatchSpaceStateClient struct {
	srpc.Stream
}

func (x *srpcSpaceResourceService_WatchSpaceStateClient) Recv() (*SpaceState, error) {
	m := new(SpaceState)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcSpaceResourceService_WatchSpaceStateClient) RecvTo(m *SpaceState) error {
	return x.MsgRecv(m)
}

func (c *srpcSpaceResourceServiceClient) WatchSpaceSharingState(ctx context.Context, in *WatchSpaceSharingStateRequest) (SRPCSpaceResourceService_WatchSpaceSharingStateClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "WatchSpaceSharingState", in)
	if err != nil {
		return nil, err
	}
	strm := &srpcSpaceResourceService_WatchSpaceSharingStateClient{stream}
	if err := strm.CloseSend(); err != nil {
		return nil, err
	}
	return strm, nil
}

type SRPCSpaceResourceService_WatchSpaceSharingStateClient interface {
	srpc.Stream
	Recv() (*SpaceSharingState, error)
	RecvTo(*SpaceSharingState) error
}

type srpcSpaceResourceService_WatchSpaceSharingStateClient struct {
	srpc.Stream
}

func (x *srpcSpaceResourceService_WatchSpaceSharingStateClient) Recv() (*SpaceSharingState, error) {
	m := new(SpaceSharingState)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcSpaceResourceService_WatchSpaceSharingStateClient) RecvTo(m *SpaceSharingState) error {
	return x.MsgRecv(m)
}

func (c *srpcSpaceResourceServiceClient) AccessWorld(ctx context.Context, in *AccessWorldRequest) (*AccessWorldResponse, error) {
	out := new(AccessWorldResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "AccessWorld", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcSpaceResourceServiceClient) MountSpaceContents(ctx context.Context, in *MountSpaceContentsRequest) (*MountSpaceContentsResponse, error) {
	out := new(MountSpaceContentsResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "MountSpaceContents", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcSpaceResourceServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest) (*CreateSecretResponse, error) {
	out := new(CreateSecretResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "CreateSecret", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcSpaceResourceServiceClient) ReadSecretPayload(ctx context.Context, in *ReadSecretPayloadRequest) (*ReadSecretPayloadResponse, error) {
	out := new(ReadSecretPayloadResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "ReadSecretPayload", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcSpaceResourceServiceClient) DeployManifests(ctx context.Context) (SRPCSpaceResourceService_DeployManifestsClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "DeployManifests", nil)
	if err != nil {
		return nil, err
	}
	strm := &srpcSpaceResourceService_DeployManifestsClient{stream}
	return strm, nil
}

type SRPCSpaceResourceService_DeployManifestsClient interface {
	srpc.Stream
	Send(*s4wave_deploy.DeployManifestsMessage) error
	Recv() (*s4wave_deploy.DeployManifestsMessage, error)
	RecvTo(*s4wave_deploy.DeployManifestsMessage) error
}

type srpcSpaceResourceService_DeployManifestsClient struct {
	srpc.Stream
}

func (x *srpcSpaceResourceService_DeployManifestsClient) Send(m *s4wave_deploy.DeployManifestsMessage) error {
	if m == nil {
		return nil
	}
	return x.MsgSend(m)
}

func (x *srpcSpaceResourceService_DeployManifestsClient) Recv() (*s4wave_deploy.DeployManifestsMessage, error) {
	m := new(s4wave_deploy.DeployManifestsMessage)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcSpaceResourceService_DeployManifestsClient) RecvTo(m *s4wave_deploy.DeployManifestsMessage) error {
	return x.MsgRecv(m)
}

func (c *srpcSpaceResourceServiceClient) AddSpacePlugin(ctx context.Context, in *AddSpacePluginRequest) (*AddSpacePluginResponse, error) {
	out := new(AddSpacePluginResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "AddSpacePlugin", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcSpaceResourceServiceClient) RemoveSpacePlugin(ctx context.Context, in *RemoveSpacePluginRequest) (*RemoveSpacePluginResponse, error) {
	out := new(RemoveSpacePluginResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "RemoveSpacePlugin", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type SRPCSpaceResourceServiceServer interface {
	WatchSpaceState(*WatchSpaceStateRequest, SRPCSpaceResourceService_WatchSpaceStateStream) error

	WatchSpaceSharingState(*WatchSpaceSharingStateRequest, SRPCSpaceResourceService_WatchSpaceSharingStateStream) error

	AccessWorld(context.Context, *AccessWorldRequest) (*AccessWorldResponse, error)

	MountSpaceContents(context.Context, *MountSpaceContentsRequest) (*MountSpaceContentsResponse, error)

	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)

	ReadSecretPayload(context.Context, *ReadSecretPayloadRequest) (*ReadSecretPayloadResponse, error)

	DeployManifests(SRPCSpaceResourceService_DeployManifestsStream) error

	AddSpacePlugin(context.Context, *AddSpacePluginRequest) (*AddSpacePluginResponse, error)

	RemoveSpacePlugin(context.Context, *RemoveSpacePluginRequest) (*RemoveSpacePluginResponse, error)
}

const SRPCSpaceResourceServiceServiceID = "s4wave.space.SpaceResourceService"

type SRPCSpaceResourceServiceHandler struct {
	serviceID string
	impl      SRPCSpaceResourceServiceServer
}

// NewSRPCSpaceResourceServiceHandler constructs a new RPC handler.
// serviceID: if empty, uses default: s4wave.space.SpaceResourceService
func NewSRPCSpaceResourceServiceHandler(impl SRPCSpaceResourceServiceServer, serviceID string) srpc.Handler {
	if serviceID == "" {
		serviceID = SRPCSpaceResourceServiceServiceID
	}
	return &SRPCSpaceResourceServiceHandler{impl: impl, serviceID: serviceID}
}

// SRPCRegisterSpaceResourceService registers the implementation with the mux.
// Uses the default serviceID: s4wave.space.SpaceResourceService
func SRPCRegisterSpaceResourceService(mux srpc.Mux, impl SRPCSpaceResourceServiceServer) error {
	return mux.Register(NewSRPCSpaceResourceServiceHandler(impl, ""))
}

func (d *SRPCSpaceResourceServiceHandler) GetServiceID() string { return d.serviceID }

func (SRPCSpaceResourceServiceHandler) GetMethodIDs() []string {
	return []string{
		"WatchSpaceState",
		"WatchSpaceSharingState",
		"AccessWorld",
		"MountSpaceContents",
		"CreateSecret",
		"ReadSecretPayload",
		"DeployManifests",
		"AddSpacePlugin",
		"RemoveSpacePlugin",
	}
}

func (d *SRPCSpaceResourceServiceHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "WatchSpaceState":
		return true, d.InvokeMethod_WatchSpaceState(d.impl, strm)
	case "WatchSpaceSharingState":
		return true, d.InvokeMethod_WatchSpaceSharingState(d.impl, strm)
	case "AccessWorld":
		return true, d.InvokeMethod_AccessWorld(d.impl, strm)
	case "MountSpaceContents":
		return true, d.InvokeMethod_MountSpaceContents(d.impl, strm)
	case "CreateSecret":
		return true, d.InvokeMethod_CreateSecret(d.impl, strm)
	case "ReadSecretPayload":
		return true, d.InvokeMethod_ReadSecretPayload(d.impl, strm)
	case "DeployManifests":
		return true, d.InvokeMethod_DeployManifests(d.impl, strm)
	case "AddSpacePlugin":
		return true, d.InvokeMethod_AddSpacePlugin(d.impl, strm)
	case "RemoveSpacePlugin":
		return true, d.InvokeMethod_RemoveSpacePlugin(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_WatchSpaceState(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(WatchSpaceStateRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	serverStrm := &srpcSpaceResourceService_WatchSpaceStateStream{strm}
	return impl.WatchSpaceState(req, serverStrm)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_WatchSpaceSharingState(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(WatchSpaceSharingStateRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	serverStrm := &srpcSpaceResourceService_WatchSpaceSharingStateStream{strm}
	return impl.WatchSpaceSharingState(req, serverStrm)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_AccessWorld(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(AccessWorldRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.AccessWorld(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_MountSpaceContents(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(MountSpaceContentsRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.MountSpaceContents(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_CreateSecret(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(CreateSecretRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.CreateSecret(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_ReadSecretPayload(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(ReadSecretPayloadRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.ReadSecretPayload(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_DeployManifests(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	clientStrm := &srpcSpaceResourceService_DeployManifestsStream{strm}
	return impl.DeployManifests(clientStrm)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_AddSpacePlugin(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(AddSpacePluginRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.AddSpacePlugin(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCSpaceResourceServiceHandler) InvokeMethod_RemoveSpacePlugin(impl SRPCSpaceResourceServiceServer, strm srpc.Stream) error {
	req := new(RemoveSpacePluginRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.RemoveSpacePlugin(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

type SRPCSpaceResourceService_WatchSpaceStateStream interface {
	srpc.Stream
	Send(*SpaceState) error
	SendAndClose(*SpaceState) error
}

type srpcSpaceResourceService_WatchSpaceStateStream struct {
	srpc.Stream
}

func (x *srpcSpaceResourceService_WatchSpaceStateStream) Send(m *SpaceState) error {
	return x.MsgSend(m)
}

func (x *srpcSpaceResourceService_WatchSpaceStateStream) SendAndClose(m *SpaceState) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}

type SRPCSpaceResourceService_WatchSpaceSharingStateStream interface {
	srpc.Stream
	Send(*SpaceSharingState) error
	SendAndClose(*SpaceSharingState) error
}

type srpcSpaceResourceService_WatchSpaceSharingStateStream struct {
	srpc.Stream
}

func (x *srpcSpaceResourceService_WatchSpaceSharingStateStream) Send(m *SpaceSharingState) error {
	return x.MsgSend(m)
}

func (x *srpcSpaceResourceService_WatchSpaceSharingStateStream) SendAndClose(m *SpaceSharingState) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}

type SRPCSpaceResourceService_AccessWorldStream interface {
	srpc.Stream
}

type srpcSpaceResourceService_AccessWorldStream struct {
	srpc.Stream
}

type SRPCSpaceResourceService_MountSpaceContentsStream interface {
	srpc.Stream
}

type srpcSpaceResourceService_MountSpaceContentsStream struct {
	srpc.Stream
}

type SRPCSpaceResourceService_CreateSecretStream interface {
	srpc.Stream
}

type srpcSpaceResourceService_CreateSecretStream struct {
	srpc.Stream
}

type SRPCSpaceResourceService_ReadSecretPayloadStream interface {
	srpc.Stream
}

type srpcSpaceResourceService_ReadSecretPayloadStream struct {
	srpc.Stream
}

type SRPCSpaceResourceService_DeployManifestsStream interface {
	srpc.Stream
	Send(*s4wave_deploy.DeployManifestsMessage) error
	SendAndClose(*s4wave_deploy.DeployManifestsMessage) error
	Recv() (*s4wave_deploy.DeployManifestsMessage, error)
	RecvTo(*s4wave_deploy.DeployManifestsMessage) error
}

type srpcSpaceResourceService_DeployManifestsStream struct {
	srpc.Stream
}

func (x *srpcSpaceResourceService_DeployManifestsStream) Send(m *s4wave_deploy.DeployManifestsMessage) error {
	return x.MsgSend(m)
}

func (x *srpcSpaceResourceService_DeployManifestsStream) SendAndClose(m *s4wave_deploy.DeployManifestsMessage) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}

func (x *srpcSpaceResourceService_DeployManifestsStream) Recv() (*s4wave_deploy.DeployManifestsMessage, error) {
	m := new(s4wave_deploy.DeployManifestsMessage)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcSpaceResourceService_DeployManifestsStream) RecvTo(m *s4wave_deploy.DeployManifestsMessage) error {
	return x.MsgRecv(m)
}

type SRPCSpaceResourceService_AddSpacePluginStream interface {
	srpc.Stream
}

type srpcSpaceResourceService_AddSpacePluginStream struct {
	srpc.Stream
}

type SRPCSpaceResourceService_RemoveSpacePluginStream interface {
	srpc.Stream
}

type srpcSpaceResourceService_RemoveSpacePluginStream struct {
	srpc.Stream
}

type SRPCSpaceContentsResourceServiceClient interface {
	// SRPCClient returns the underlying SRPC client.
	SRPCClient() srpc.Client

	WatchState(ctx context.Context, in *WatchSpaceContentsStateRequest) (SRPCSpaceContentsResourceService_WatchStateClient, error)

	SetProcessBinding(ctx context.Context, in *SetProcessBindingRequest) (*SetProcessBindingResponse, error)
	// BindAttachedRpcService publishes a caller-attached Resource under one
	// private service ID prefix for this Space runtime.
	BindAttachedRpcService(ctx context.Context, in *BindAttachedRpcServiceRequest) (SRPCSpaceContentsResourceService_BindAttachedRpcServiceClient, error)
}

type srpcSpaceContentsResourceServiceClient struct {
	cc        srpc.Client
	serviceID string
}

func NewSRPCSpaceContentsResourceServiceClient(cc srpc.Client) SRPCSpaceContentsResourceServiceClient {
	return &srpcSpaceContentsResourceServiceClient{cc: cc, serviceID: SRPCSpaceContentsResourceServiceServiceID}
}

func NewSRPCSpaceContentsResourceServiceClientWithServiceID(cc srpc.Client, serviceID string) SRPCSpaceContentsResourceServiceClient {
	if serviceID == "" {
		serviceID = SRPCSpaceContentsResourceServiceServiceID
	}
	return &srpcSpaceContentsResourceServiceClient{cc: cc, serviceID: serviceID}
}

func (c *srpcSpaceContentsResourceServiceClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcSpaceContentsResourceServiceClient) WatchState(ctx context.Context, in *WatchSpaceContentsStateRequest) (SRPCSpaceContentsResourceService_WatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "WatchState", in)
	if err != nil {
		return nil, err
	}
	strm := &srpcSpaceContentsResourceService_WatchStateClient{stream}
	if err := strm.CloseSend(); err != nil {
		return nil, err
	}
	return strm, nil
}

type SRPCSpaceContentsResourceService_WatchStateClient interface {
	srpc.Stream
	Recv() (*SpaceContentsState, error)
	RecvTo(*SpaceContentsState) error
}

type srpcSpaceContentsResourceService_WatchStateClient struct {
	srpc.Stream
}

func (x *srpcSpaceContentsResourceService_WatchStateClient) Recv() (*SpaceContentsState, error) {
	m := new(SpaceContentsState)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcSpaceContentsResourceService_WatchStateClient) RecvTo(m *SpaceContentsState) error {
	return x.MsgRecv(m)
}

func (c *srpcSpaceContentsResourceServiceClient) SetProcessBinding(ctx context.Context, in *SetProcessBindingRequest) (*SetProcessBindingResponse, error) {
	out := new(SetProcessBindingResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "SetProcessBinding", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcSpaceContentsResourceServiceClient) BindAttachedRpcService(ctx context.Context, in *BindAttachedRpcServiceRequest) (SRPCSpaceContentsResourceService_BindAttachedRpcServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "BindAttachedRpcService", in)
	if err != nil {
		return nil, err
	}
	strm := &srpcSpaceContentsResourceService_BindAttachedRpcServiceClient{stream}
	if err := strm.CloseSend(); err != nil {
		return nil, err
	}
	return strm, nil
}

type SRPCSpaceContentsResourceService_BindAttachedRpcServiceClient interface {
	srpc.Stream
	Recv() (*BindAttachedRpcServiceResponse, error)
	RecvTo(*BindAttachedRpcServiceResponse) error
}

type srpcSpaceContentsResourceService_BindAttachedRpcServiceClient struct {
	srpc.Stream
}

func (x *srpcSpaceContentsResourceService_BindAttachedRpcServiceClient) Recv() (*BindAttachedRpcServiceResponse, error) {
	m := new(BindAttachedRpcServiceResponse)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcSpaceContentsResourceService_BindAttachedRpcServiceClient) RecvTo(m *BindAttachedRpcServiceResponse) error {
	return x.MsgRecv(m)
}

type SRPCSpaceContentsResourceServiceServer interface {
	WatchState(*WatchSpaceContentsStateRequest, SRPCSpaceContentsResourceService_WatchStateStream) error

	SetProcessBinding(context.Context, *SetProcessBindingRequest) (*SetProcessBindingResponse, error)
	// BindAttachedRpcService publishes a caller-attached Resource under one
	// private service ID prefix for this Space runtime.
	BindAttachedRpcService(*BindAttachedRpcServiceRequest, SRPCSpaceContentsResourceService_BindAttachedRpcServiceStream) error
}

const SRPCSpaceContentsResourceServiceServiceID = "s4wave.space.SpaceContentsResourceService"

type SRPCSpaceContentsResourceServiceHandler struct {
	serviceID string
	impl      SRPCSpaceContentsResourceServiceServer
}

// NewSRPCSpaceContentsResourceServiceHandler constructs a new RPC handler.
// serviceID: if empty, uses default: s4wave.space.SpaceContentsResourceService
func NewSRPCSpaceContentsResourceServiceHandler(impl SRPCSpaceContentsResourceServiceServer, serviceID string) srpc.Handler {
	if serviceID == "" {
		serviceID = SRPCSpaceContentsResourceServiceServiceID
	}
	return &SRPCSpaceContentsResourceServiceHandler{impl: impl, serviceID: serviceID}
}

// SRPCRegisterSpaceContentsResourceService registers the implementation with the mux.
// Uses the default serviceID: s4wave.space.SpaceContentsResourceService
func SRPCRegisterSpaceContentsResourceService(mux srpc.Mux, impl SRPCSpaceContentsResourceServiceServer) error {
	return mux.Register(NewSRPCSpaceContentsResourceServiceHandler(impl, ""))
}

func (d *SRPCSpaceContentsResourceServiceHandler) GetServiceID() string { return d.serviceID }

func (SRPCSpaceContentsResourceServiceHandler) GetMethodIDs() []string {
	return []string{
		"WatchState",
		"SetProcessBinding",
		"BindAttachedRpcService",
	}
}

func (d *SRPCSpaceContentsResourceServiceHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "WatchState":
		return true, d.InvokeMethod_WatchState(d.impl, strm)
	case "SetProcessBinding":
		return true, d.InvokeMethod_SetProcessBinding(d.impl, strm)
	case "BindAttachedRpcService":
		return true, d.InvokeMethod_BindAttachedRpcService(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCSpaceContentsResourceServiceHandler) InvokeMethod_WatchState(impl SRPCSpaceContentsResourceServiceServer, strm srpc.Stream) error {
	req := new(WatchSpaceContentsStateRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	serverStrm := &srpcSpaceContentsResourceService_WatchStateStream{strm}
	return impl.WatchState(req, serverStrm)
}

func (SRPCSpaceContentsResourceServiceHandler) InvokeMethod_SetProcessBinding(impl SRPCSpaceContentsResourceServiceServer, strm srpc.Stream) error {
	req := new(SetProcessBindingRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.SetProcessBinding(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCSpaceContentsResourceServiceHandler) InvokeMethod_BindAttachedRpcService(impl SRPCSpaceContentsResourceServiceServer, strm srpc.Stream) error {
	req := new(BindAttachedRpcServiceRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	serverStrm := &srpcSpaceContentsResourceService_BindAttachedRpcServiceStream{strm}
	return impl.BindAttachedRpcService(req, serverStrm)
}

type SRPCSpaceContentsResourceService_WatchStateStream interface {
	srpc.Stream
	Send(*SpaceContentsState) error
	SendAndClose(*SpaceContentsState) error
}

type srpcSpaceContentsResourceService_WatchStateStream struct {
	srpc.Stream
}

func (x *srpcSpaceContentsResourceService_WatchStateStream) Send(m *SpaceContentsState) error {
	return x.MsgSend(m)
}

func (x *srpcSpaceContentsResourceService_WatchStateStream) SendAndClose(m *SpaceContentsState) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}

type SRPCSpaceContentsResourceService_SetProcessBindingStream interface {
	srpc.Stream
}

type srpcSpaceContentsResourceService_SetProcessBindingStream struct {
	srpc.Stream
}

type SRPCSpaceContentsResourceService_BindAttachedRpcServiceStream interface {
	srpc.Stream
	Send(*BindAttachedRpcServiceResponse) error
	SendAndClose(*BindAttachedRpcServiceResponse) error
}

type srpcSpaceContentsResourceService_BindAttachedRpcServiceStream struct {
	srpc.Stream
}

func (x *srpcSpaceContentsResourceService_BindAttachedRpcServiceStream) Send(m *BindAttachedRpcServiceResponse) error {
	return x.MsgSend(m)
}

func (x *srpcSpaceContentsResourceService_BindAttachedRpcServiceStream) SendAndClose(m *BindAttachedRpcServiceResponse) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}
