// Code generated by protoc-gen-srpc. DO NOT EDIT.
// protoc-gen-srpc version: v0.52.1
// source: github.com/s4wave/spacewave/bldr/web/view/handler/rpc.proto

package web_view_handler

import (
	context "context"

	srpc "github.com/aperturerobotics/starpc/srpc"
)

type SRPCHandleWebViewServiceClient interface {
	// SRPCClient returns the underlying SRPC client.
	SRPCClient() srpc.Client

	// HandleWebView handles a web view via rpc.
	// The RPC will be held open while the handler runs.
	// The RPC is canceled if the WebView is removed.
	// The handler can access the WebView service via AccessWebViews.
	HandleWebView(ctx context.Context, in *HandleWebViewRequest) (*HandleWebViewResponse, error)
}

type srpcHandleWebViewServiceClient struct {
	cc        srpc.Client
	serviceID string
}

func NewSRPCHandleWebViewServiceClient(cc srpc.Client) SRPCHandleWebViewServiceClient {
	return &srpcHandleWebViewServiceClient{cc: cc, serviceID: SRPCHandleWebViewServiceServiceID}
}

func NewSRPCHandleWebViewServiceClientWithServiceID(cc srpc.Client, serviceID string) SRPCHandleWebViewServiceClient {
	if serviceID == "" {
		serviceID = SRPCHandleWebViewServiceServiceID
	}
	return &srpcHandleWebViewServiceClient{cc: cc, serviceID: serviceID}
}

func (c *srpcHandleWebViewServiceClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcHandleWebViewServiceClient) HandleWebView(ctx context.Context, in *HandleWebViewRequest) (*HandleWebViewResponse, error) {
	out := new(HandleWebViewResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "HandleWebView", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type SRPCHandleWebViewServiceServer interface {
	// HandleWebView handles a web view via rpc.
	// The RPC will be held open while the handler runs.
	// The RPC is canceled if the WebView is removed.
	// The handler can access the WebView service via AccessWebViews.
	HandleWebView(context.Context, *HandleWebViewRequest) (*HandleWebViewResponse, error)
}

const SRPCHandleWebViewServiceServiceID = "web.view.handler.HandleWebViewService"

type SRPCHandleWebViewServiceHandler struct {
	serviceID string
	impl      SRPCHandleWebViewServiceServer
}

// NewSRPCHandleWebViewServiceHandler constructs a new RPC handler.
// serviceID: if empty, uses default: web.view.handler.HandleWebViewService
func NewSRPCHandleWebViewServiceHandler(impl SRPCHandleWebViewServiceServer, serviceID string) srpc.Handler {
	if serviceID == "" {
		serviceID = SRPCHandleWebViewServiceServiceID
	}
	return &SRPCHandleWebViewServiceHandler{impl: impl, serviceID: serviceID}
}

// SRPCRegisterHandleWebViewService registers the implementation with the mux.
// Uses the default serviceID: web.view.handler.HandleWebViewService
func SRPCRegisterHandleWebViewService(mux srpc.Mux, impl SRPCHandleWebViewServiceServer) error {
	return mux.Register(NewSRPCHandleWebViewServiceHandler(impl, ""))
}

func (d *SRPCHandleWebViewServiceHandler) GetServiceID() string { return d.serviceID }

func (SRPCHandleWebViewServiceHandler) GetMethodIDs() []string {
	return []string{
		"HandleWebView",
	}
}

func (d *SRPCHandleWebViewServiceHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "HandleWebView":
		return true, d.InvokeMethod_HandleWebView(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCHandleWebViewServiceHandler) InvokeMethod_HandleWebView(impl SRPCHandleWebViewServiceServer, strm srpc.Stream) error {
	req := new(HandleWebViewRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.HandleWebView(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

type SRPCHandleWebViewService_HandleWebViewStream interface {
	srpc.Stream
}

type srpcHandleWebViewService_HandleWebViewStream struct {
	srpc.Stream
}
