//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/bifrost/transport/common/pconn/pconn.proto
// Protobuf C++ Version: 6.33.4

#include "pconn.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pconn {

inline constexpr Opts::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        quic_{nullptr},
        verbose_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Opts::Opts(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Opts_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OptsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptsDefaultTypeInternal() {}
  union {
    Opts _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptsDefaultTypeInternal _Opts_default_instance_;
}  // namespace pconn
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pconn::Opts, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pconn::Opts, _impl_.quic_),
        PROTOBUF_FIELD_OFFSET(::pconn::Opts, _impl_.verbose_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::pconn::Opts)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::pconn::_Opts_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\nFgithub.com/aperturerobotics/bifrost/tr"
    "ansport/common/pconn/pconn.proto\022\005pconn\032"
    "Dgithub.com/aperturerobotics/bifrost/tra"
    "nsport/common/quic/quic.proto\";\n\004Opts\022\"\n"
    "\004quic\030\001 \001(\0132\024.transport.quic.Opts\022\017\n\007ver"
    "bose\030\002 \001(\010b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto_deps[1] = {
        &::descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fquic_2fquic_2eproto,
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto = {
    false,
    false,
    218,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto,
    "github.com/aperturerobotics/bifrost/transport/common/pconn/pconn.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto_once,
    descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto,
};
namespace pconn {
// ===================================================================

class Opts::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Opts>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Opts, _impl_._has_bits_);
};

void Opts::clear_quic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.quic_ != nullptr) _impl_.quic_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
Opts::Opts(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Opts_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pconn.Opts)
}
PROTOBUF_NDEBUG_INLINE Opts::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::pconn::Opts& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Opts::Opts(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Opts& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Opts_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Opts* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.quic_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.quic_)
                : nullptr;
  _impl_.verbose_ = from._impl_.verbose_;

  // @@protoc_insertion_point(copy_constructor:pconn.Opts)
}
PROTOBUF_NDEBUG_INLINE Opts::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Opts::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, quic_),
           0,
           offsetof(Impl_, verbose_) -
               offsetof(Impl_, quic_) +
               sizeof(Impl_::verbose_));
}
Opts::~Opts() {
  // @@protoc_insertion_point(destructor:pconn.Opts)
  SharedDtor(*this);
}
inline void Opts::SharedDtor(MessageLite& self) {
  Opts& this_ = static_cast<Opts&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.quic_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Opts::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Opts(arena);
}
constexpr auto Opts::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Opts),
                                            alignof(Opts));
}
constexpr auto Opts::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Opts_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Opts::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Opts>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Opts::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Opts>(), &Opts::ByteSizeLong,
              &Opts::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Opts, _impl_._cached_size_),
          false,
      },
      &Opts::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Opts_class_data_ =
        Opts::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Opts::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Opts_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Opts_class_data_.tc_table);
  return Opts_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
Opts::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Opts, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Opts_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pconn::Opts>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool verbose = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Opts, _impl_.verbose_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(Opts, _impl_.verbose_)}},
    // .transport.quic.Opts quic = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Opts, _impl_.quic_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .transport.quic.Opts quic = 1;
    {PROTOBUF_FIELD_OFFSET(Opts, _impl_.quic_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool verbose = 2;
    {PROTOBUF_FIELD_OFFSET(Opts, _impl_.verbose_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::transport::quic::Opts>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Opts::Clear() {
// @@protoc_insertion_point(message_clear_start:pconn.Opts)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.quic_ != nullptr);
    _impl_.quic_->Clear();
  }
  _impl_.verbose_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Opts::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Opts& this_ = static_cast<const Opts&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Opts::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Opts& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pconn.Opts)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .transport.quic.Opts quic = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.quic_, this_._impl_.quic_->GetCachedSize(), target,
        stream);
  }

  // bool verbose = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_verbose() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_verbose(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pconn.Opts)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Opts::ByteSizeLong(const MessageLite& base) {
  const Opts& this_ = static_cast<const Opts&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Opts::ByteSizeLong() const {
  const Opts& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pconn.Opts)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .transport.quic.Opts quic = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.quic_);
    }
    // bool verbose = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_verbose() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Opts::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Opts*>(&to_msg);
  auto& from = static_cast<const Opts&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:pconn.Opts)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.quic_ != nullptr);
      if (_this->_impl_.quic_ == nullptr) {
        _this->_impl_.quic_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.quic_);
      } else {
        _this->_impl_.quic_->MergeFrom(*from._impl_.quic_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_verbose() != 0) {
        _this->_impl_.verbose_ = from._impl_.verbose_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Opts::CopyFrom(const Opts& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pconn.Opts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Opts::InternalSwap(Opts* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Opts, _impl_.verbose_)
      + sizeof(Opts::_impl_.verbose_)
      - PROTOBUF_FIELD_OFFSET(Opts, _impl_.quic_)>(
          reinterpret_cast<char*>(&_impl_.quic_),
          reinterpret_cast<char*>(&other->_impl_.quic_));
}

::google::protobuf::Metadata Opts::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace pconn
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fbifrost_2ftransport_2fcommon_2fpconn_2fpconn_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
