* SSH over Xbee Example

** Xbee Setup

Reset the xbees to default values, then set:

 - AP: 2 (API mode with escapes)
 - Baud: 115200
 
You may need to edit the yaml files to change the path to the serial device.

** Node 1

Peer ID: 12D3KooWC9dBAEoTHbEXq2aaTeFit7QVdvPcb6Yf76oGQZ6dGf8N 
SSH daemon listening on port 22
XBee at /dev/ttyUSB0

#+BEGIN_SRC
  bifrost daemon --node-priv ../priv/node-1.pem -c node-1.yaml
#+END_SRC

When you execute the daemon, the address is printed:

#+BEGIN_SRC text
INFO[0000] opened xbee device successfully
               controller=bifrost/xbee/1
               device-address=0013a20040db7492 
               device-baud=115200 device-path=/dev/ttyUSB0
#+END_SRC

You should copy the address into the node-2.yaml file for your xbee setup.

** Node 2

Peer ID: 12D3KooWJukwYJ46o4uYSApGHAZrjrZPLHqt3EVy1etas2KVn9RP 

Port 8084 forwards through to port 8080 on node 1.

Remember to edit node-2.yaml and change the xbee address for node-1.

#+BEGIN_SRC
bifrost daemon --api-listen :5111 --node-priv ../priv/node-2.pem -c node-2.yaml
ssh -p 2000 root@localhost
#+END_SRC

Bifrost will listen on port 2000, accept the TCP connection, forward it through
to node-1, and proxy the SSH session over the wire.

Experiment with editing the configs and changing the block crypto and
compression settings.

