// Code generated by protoc-gen-srpc. DO NOT EDIT.
// protoc-gen-srpc version: v0.52.1
// source: github.com/s4wave/spacewave/bldr/manifest/manifest.proto

package bldr_manifest

import (
	context "context"

	srpc "github.com/aperturerobotics/starpc/srpc"
)

type SRPCManifestFetchClient interface {
	// SRPCClient returns the underlying SRPC client.
	SRPCClient() srpc.Client

	// FetchManifest requests the manifest for the given metadata.
	// The metadata may not be an exact match.
	// Returns the stream of values from the FetchManifest directive.
	FetchManifest(ctx context.Context, in *FetchManifestRequest) (SRPCManifestFetch_FetchManifestClient, error)
}

type srpcManifestFetchClient struct {
	cc        srpc.Client
	serviceID string
}

func NewSRPCManifestFetchClient(cc srpc.Client) SRPCManifestFetchClient {
	return &srpcManifestFetchClient{cc: cc, serviceID: SRPCManifestFetchServiceID}
}

func NewSRPCManifestFetchClientWithServiceID(cc srpc.Client, serviceID string) SRPCManifestFetchClient {
	if serviceID == "" {
		serviceID = SRPCManifestFetchServiceID
	}
	return &srpcManifestFetchClient{cc: cc, serviceID: serviceID}
}

func (c *srpcManifestFetchClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcManifestFetchClient) FetchManifest(ctx context.Context, in *FetchManifestRequest) (SRPCManifestFetch_FetchManifestClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "FetchManifest", in)
	if err != nil {
		return nil, err
	}
	strm := &srpcManifestFetch_FetchManifestClient{stream}
	if err := strm.CloseSend(); err != nil {
		return nil, err
	}
	return strm, nil
}

type SRPCManifestFetch_FetchManifestClient interface {
	srpc.Stream
	Recv() (*FetchManifestResponse, error)
	RecvTo(*FetchManifestResponse) error
}

type srpcManifestFetch_FetchManifestClient struct {
	srpc.Stream
}

func (x *srpcManifestFetch_FetchManifestClient) Recv() (*FetchManifestResponse, error) {
	m := new(FetchManifestResponse)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcManifestFetch_FetchManifestClient) RecvTo(m *FetchManifestResponse) error {
	return x.MsgRecv(m)
}

type SRPCManifestFetchServer interface {
	// FetchManifest requests the manifest for the given metadata.
	// The metadata may not be an exact match.
	// Returns the stream of values from the FetchManifest directive.
	FetchManifest(*FetchManifestRequest, SRPCManifestFetch_FetchManifestStream) error
}

const SRPCManifestFetchServiceID = "bldr.manifest.ManifestFetch"

type SRPCManifestFetchHandler struct {
	serviceID string
	impl      SRPCManifestFetchServer
}

// NewSRPCManifestFetchHandler constructs a new RPC handler.
// serviceID: if empty, uses default: bldr.manifest.ManifestFetch
func NewSRPCManifestFetchHandler(impl SRPCManifestFetchServer, serviceID string) srpc.Handler {
	if serviceID == "" {
		serviceID = SRPCManifestFetchServiceID
	}
	return &SRPCManifestFetchHandler{impl: impl, serviceID: serviceID}
}

// SRPCRegisterManifestFetch registers the implementation with the mux.
// Uses the default serviceID: bldr.manifest.ManifestFetch
func SRPCRegisterManifestFetch(mux srpc.Mux, impl SRPCManifestFetchServer) error {
	return mux.Register(NewSRPCManifestFetchHandler(impl, ""))
}

func (d *SRPCManifestFetchHandler) GetServiceID() string { return d.serviceID }

func (SRPCManifestFetchHandler) GetMethodIDs() []string {
	return []string{
		"FetchManifest",
	}
}

func (d *SRPCManifestFetchHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "FetchManifest":
		return true, d.InvokeMethod_FetchManifest(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCManifestFetchHandler) InvokeMethod_FetchManifest(impl SRPCManifestFetchServer, strm srpc.Stream) error {
	req := new(FetchManifestRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	serverStrm := &srpcManifestFetch_FetchManifestStream{strm}
	return impl.FetchManifest(req, serverStrm)
}

type SRPCManifestFetch_FetchManifestStream interface {
	srpc.Stream
	Send(*FetchManifestResponse) error
	SendAndClose(*FetchManifestResponse) error
}

type srpcManifestFetch_FetchManifestStream struct {
	srpc.Stream
}

func (x *srpcManifestFetch_FetchManifestStream) Send(m *FetchManifestResponse) error {
	return x.MsgSend(m)
}

func (x *srpcManifestFetch_FetchManifestStream) SendAndClose(m *FetchManifestResponse) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}
