// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.18.1-0.20260826222423-298dca0e6eaf
// source: github.com/s4wave/spacewave/sdk/chat/chat.proto

package spacewave_chat

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	timestamppb "github.com/aperturerobotics/protobuf-go-lite/types/known/timestamppb"
	content "github.com/s4wave/spacewave/sdk/chat/content"
	state "github.com/s4wave/spacewave/sdk/chat/state"
)

// ChatChannel is a chat channel world object.
// All channels are visible to Space participants (no visibility field).
type ChatChannel struct {
	unknownFields []byte
	// Name is the channel display name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Topic is an optional channel topic description.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// CreatedAt is the creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty"`
	// MessageCount is the number of messages appended to the channel.
	MessageCount uint64 `protobuf:"varint,4,opt,name=message_count,json=messageCount,proto3" json:"messageCount,omitempty"`
	// ReadPositions maps verified person peer identities to their shared read positions.
	// Keys are external cryptographic identities, not World object references.
	ReadPositions map[string]*state.ChatReadPosition `protobuf:"bytes,5,rep,name=read_positions,json=readPositions,proto3" json:"readPositions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// CreatorPeerId is the peer identity that created the channel.
	CreatorPeerId string `protobuf:"bytes,6,opt,name=creator_peer_id,json=creatorPeerId,proto3" json:"creatorPeerId,omitempty"`
	// EncryptionAlgorithm is the immutable creation-time policy. Empty allows plaintext;
	// otherwise message bodies require this algorithm; typed annotations remain public.
	EncryptionAlgorithm string `protobuf:"bytes,7,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryptionAlgorithm,omitempty"`
}

func (x *ChatChannel) Reset() {
	*x = ChatChannel{}
}

func (*ChatChannel) ProtoMessage() {}

func (x *ChatChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatChannel) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ChatChannel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatChannel) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ChatChannel) GetReadPositions() map[string]*state.ChatReadPosition {
	if x != nil {
		return x.ReadPositions
	}
	return nil
}

func (x *ChatChannel) GetCreatorPeerId() string {
	if x != nil {
		return x.CreatorPeerId
	}
	return ""
}

func (x *ChatChannel) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

// ChatMessage is a chat message world object linked to a channel.
type ChatMessage struct {
	unknownFields []byte
	// SenderPeerId is the peer ID of the message sender.
	SenderPeerId string `protobuf:"bytes,1,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"senderPeerId,omitempty"`
	// Content is the message content.
	Content *content.ChatMessageContent `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// CreatedAt is the message creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty"`
	// ReplyToKey is the object key of the message being replied to.
	ReplyToKey string `protobuf:"bytes,4,opt,name=reply_to_key,json=replyToKey,proto3" json:"replyToKey,omitempty"`
	// Index is the zero-based message index within the channel.
	Index uint64 `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	// PersonPeerId is the verified person identity supplied by the authenticated host.
	// Empty historical values identify the person by SenderPeerId.
	PersonPeerId string `protobuf:"bytes,6,opt,name=person_peer_id,json=personPeerId,proto3" json:"personPeerId,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) GetSenderPeerId() string {
	if x != nil {
		return x.SenderPeerId
	}
	return ""
}

func (x *ChatMessage) GetContent() *content.ChatMessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatMessage) GetReplyToKey() string {
	if x != nil {
		return x.ReplyToKey
	}
	return ""
}

func (x *ChatMessage) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatMessage) GetPersonPeerId() string {
	if x != nil {
		return x.PersonPeerId
	}
	return ""
}

// ChatMessagePage stores a bounded page of channel message keys.
type ChatMessagePage struct {
	unknownFields []byte
	// MessageKeys are page-local message object keys in creation order.
	MessageKeys []string `protobuf:"bytes,1,rep,name=message_keys,json=messageKeys,proto3" json:"messageKeys,omitempty"`
}

func (x *ChatMessagePage) Reset() {
	*x = ChatMessagePage{}
}

func (*ChatMessagePage) ProtoMessage() {}

func (x *ChatMessagePage) GetMessageKeys() []string {
	if x != nil {
		return x.MessageKeys
	}
	return nil
}

// InitChatDemoOp creates a "General" channel on space quickstart.
type InitChatDemoOp struct {
	unknownFields []byte
	// ChannelObjectKey is the key for the channel object.
	ChannelObjectKey string `protobuf:"bytes,1,opt,name=channel_object_key,json=channelObjectKey,proto3" json:"channelObjectKey,omitempty"`
	// Timestamp is the creation timestamp.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *InitChatDemoOp) Reset() {
	*x = InitChatDemoOp{}
}

func (*InitChatDemoOp) ProtoMessage() {}

func (x *InitChatDemoOp) GetChannelObjectKey() string {
	if x != nil {
		return x.ChannelObjectKey
	}
	return ""
}

func (x *InitChatDemoOp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CreateChatChannelOp creates a new chat channel.
type CreateChatChannelOp struct {
	unknownFields []byte
	// ObjectKey is the key to create the channel at.
	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"objectKey,omitempty"`
	// Name is the channel name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Topic is the optional channel topic.
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// Timestamp is the creation timestamp.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// EncryptionAlgorithm is the immutable creation-time policy. Empty allows plaintext;
	// otherwise message bodies require this algorithm; typed annotations remain public.
	EncryptionAlgorithm string `protobuf:"bytes,5,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryptionAlgorithm,omitempty"`
}

func (x *CreateChatChannelOp) Reset() {
	*x = CreateChatChannelOp{}
}

func (*CreateChatChannelOp) ProtoMessage() {}

func (x *CreateChatChannelOp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CreateChatChannelOp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatChannelOp) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateChatChannelOp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CreateChatChannelOp) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

type ChatChannel_ReadPositionsEntry struct {
	unknownFields []byte
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *state.ChatReadPosition `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ChatChannel_ReadPositionsEntry) Reset() {
	*x = ChatChannel_ReadPositionsEntry{}
}

func (*ChatChannel_ReadPositionsEntry) ProtoMessage() {}

func (x *ChatChannel_ReadPositionsEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatChannel_ReadPositionsEntry) GetValue() *state.ChatReadPosition {
	if x != nil {
		return x.Value
	}
	return nil
}

func (m *ChatChannel) CloneVT() *ChatChannel {
	if m == nil {
		return (*ChatChannel)(nil)
	}
	r := new(ChatChannel)
	r.Name = m.Name
	r.Topic = m.Topic
	r.MessageCount = m.MessageCount
	r.CreatorPeerId = m.CreatorPeerId
	r.EncryptionAlgorithm = m.EncryptionAlgorithm
	r.CreatedAt = protobuf_go_lite.CloneVTValue(m.CreatedAt)
	r.ReadPositions = protobuf_go_lite.CloneVTMap(m.ReadPositions)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ChatChannel) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *ChatMessage) CloneVT() *ChatMessage {
	if m == nil {
		return (*ChatMessage)(nil)
	}
	r := new(ChatMessage)
	r.SenderPeerId = m.SenderPeerId
	r.ReplyToKey = m.ReplyToKey
	r.Index = m.Index
	r.PersonPeerId = m.PersonPeerId
	r.Content = protobuf_go_lite.CloneVTValue(m.Content)
	r.CreatedAt = protobuf_go_lite.CloneVTValue(m.CreatedAt)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ChatMessage) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *ChatMessagePage) CloneVT() *ChatMessagePage {
	if m == nil {
		return (*ChatMessagePage)(nil)
	}
	r := new(ChatMessagePage)
	r.MessageKeys = protobuf_go_lite.CloneSlice(m.MessageKeys)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ChatMessagePage) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *InitChatDemoOp) CloneVT() *InitChatDemoOp {
	if m == nil {
		return (*InitChatDemoOp)(nil)
	}
	r := new(InitChatDemoOp)
	r.ChannelObjectKey = m.ChannelObjectKey
	r.Timestamp = protobuf_go_lite.CloneVTValue(m.Timestamp)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *InitChatDemoOp) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CreateChatChannelOp) CloneVT() *CreateChatChannelOp {
	if m == nil {
		return (*CreateChatChannelOp)(nil)
	}
	r := new(CreateChatChannelOp)
	r.ObjectKey = m.ObjectKey
	r.Name = m.Name
	r.Topic = m.Topic
	r.EncryptionAlgorithm = m.EncryptionAlgorithm
	r.Timestamp = protobuf_go_lite.CloneVTValue(m.Timestamp)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CreateChatChannelOp) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *ChatChannel) EqualVT(that *ChatChannel) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.Topic != that.Topic {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.CreatedAt, that.CreatedAt) {
		return false
	}
	if this.MessageCount != that.MessageCount {
		return false
	}
	if !protobuf_go_lite.EqualVTMapImplicit(this.ReadPositions, that.ReadPositions, func() *state.ChatReadPosition { return &state.ChatReadPosition{} }) {
		return false
	}
	if this.CreatorPeerId != that.CreatorPeerId {
		return false
	}
	if this.EncryptionAlgorithm != that.EncryptionAlgorithm {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ChatChannel) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ChatChannel)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *ChatMessage) EqualVT(that *ChatMessage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.SenderPeerId != that.SenderPeerId {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Content, that.Content) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.CreatedAt, that.CreatedAt) {
		return false
	}
	if this.ReplyToKey != that.ReplyToKey {
		return false
	}
	if this.Index != that.Index {
		return false
	}
	if this.PersonPeerId != that.PersonPeerId {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ChatMessage) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ChatMessage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *ChatMessagePage) EqualVT(that *ChatMessagePage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.MessageKeys, that.MessageKeys) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ChatMessagePage) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ChatMessagePage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *InitChatDemoOp) EqualVT(that *InitChatDemoOp) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.ChannelObjectKey != that.ChannelObjectKey {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Timestamp, that.Timestamp) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *InitChatDemoOp) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*InitChatDemoOp)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CreateChatChannelOp) EqualVT(that *CreateChatChannelOp) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.ObjectKey != that.ObjectKey {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.Topic != that.Topic {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Timestamp, that.Timestamp) {
		return false
	}
	if this.EncryptionAlgorithm != that.EncryptionAlgorithm {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CreateChatChannelOp) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CreateChatChannelOp)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the ChatChannel_ReadPositionsEntry message to JSON.
func (x *ChatChannel_ReadPositionsEntry) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Key != "" || s.HasField("key") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("key")
		s.WriteString(x.Key)
	}
	if x.Value != nil || s.HasField("value") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("value")
		x.Value.MarshalProtoJSON(s.WithField("value"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ChatChannel_ReadPositionsEntry to JSON.
func (x *ChatChannel_ReadPositionsEntry) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ChatChannel_ReadPositionsEntry message from JSON.
func (x *ChatChannel_ReadPositionsEntry) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "key":
			s.AddField("key")
			x.Key = s.ReadString()
		case "value":
			if s.ReadNil() {
				x.Value = nil
				return
			}
			x.Value = &state.ChatReadPosition{}
			x.Value.UnmarshalProtoJSON(s.WithField("value", true))
		}
	})
}

// UnmarshalJSON unmarshals the ChatChannel_ReadPositionsEntry from JSON.
func (x *ChatChannel_ReadPositionsEntry) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ChatChannel message to JSON.
func (x *ChatChannel) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Name != "" || s.HasField("name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteString(x.Name)
	}
	if x.Topic != "" || s.HasField("topic") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("topic")
		s.WriteString(x.Topic)
	}
	if x.CreatedAt != nil || s.HasField("createdAt") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("createdAt")
		x.CreatedAt.MarshalProtoJSON(s.WithField("createdAt"))
	}
	if x.MessageCount != 0 || s.HasField("messageCount") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("messageCount")
		s.WriteUint64(x.MessageCount)
	}
	if x.ReadPositions != nil || s.HasField("readPositions") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("readPositions")
		s.WriteObjectStart()
		var wroteElement bool
		for k, v := range x.ReadPositions {
			s.WriteMoreIf(&wroteElement)
			s.WriteObjectStringField(k)
			v.MarshalProtoJSON(s.WithField("readPositions"))
		}
		s.WriteObjectEnd()
	}
	if x.CreatorPeerId != "" || s.HasField("creatorPeerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("creatorPeerId")
		s.WriteString(x.CreatorPeerId)
	}
	if x.EncryptionAlgorithm != "" || s.HasField("encryptionAlgorithm") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("encryptionAlgorithm")
		s.WriteString(x.EncryptionAlgorithm)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ChatChannel to JSON.
func (x *ChatChannel) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ChatChannel message from JSON.
func (x *ChatChannel) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "name":
			s.AddField("name")
			x.Name = s.ReadString()
		case "topic":
			s.AddField("topic")
			x.Topic = s.ReadString()
		case "created_at", "createdAt":
			if s.ReadNil() {
				x.CreatedAt = nil
				return
			}
			x.CreatedAt = &timestamppb.Timestamp{}
			x.CreatedAt.UnmarshalProtoJSON(s.WithField("created_at", true))
		case "message_count", "messageCount":
			s.AddField("message_count")
			x.MessageCount = s.ReadUint64()
		case "read_positions", "readPositions":
			s.AddField("read_positions")
			if s.ReadNil() {
				x.ReadPositions = nil
				return
			}
			x.ReadPositions = make(map[string]*state.ChatReadPosition)
			s.ReadStringMap(func(key string) {
				var v state.ChatReadPosition
				v.UnmarshalProtoJSON(s)
				x.ReadPositions[key] = &v
			})
		case "creator_peer_id", "creatorPeerId":
			s.AddField("creator_peer_id")
			x.CreatorPeerId = s.ReadString()
		case "encryption_algorithm", "encryptionAlgorithm":
			s.AddField("encryption_algorithm")
			x.EncryptionAlgorithm = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the ChatChannel from JSON.
func (x *ChatChannel) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ChatMessage message to JSON.
func (x *ChatMessage) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.SenderPeerId != "" || s.HasField("senderPeerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("senderPeerId")
		s.WriteString(x.SenderPeerId)
	}
	if x.Content != nil || s.HasField("content") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("content")
		x.Content.MarshalProtoJSON(s.WithField("content"))
	}
	if x.CreatedAt != nil || s.HasField("createdAt") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("createdAt")
		x.CreatedAt.MarshalProtoJSON(s.WithField("createdAt"))
	}
	if x.ReplyToKey != "" || s.HasField("replyToKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("replyToKey")
		s.WriteString(x.ReplyToKey)
	}
	if x.Index != 0 || s.HasField("index") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("index")
		s.WriteUint64(x.Index)
	}
	if x.PersonPeerId != "" || s.HasField("personPeerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("personPeerId")
		s.WriteString(x.PersonPeerId)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ChatMessage to JSON.
func (x *ChatMessage) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ChatMessage message from JSON.
func (x *ChatMessage) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "sender_peer_id", "senderPeerId":
			s.AddField("sender_peer_id")
			x.SenderPeerId = s.ReadString()
		case "content":
			if s.ReadNil() {
				x.Content = nil
				return
			}
			x.Content = &content.ChatMessageContent{}
			x.Content.UnmarshalProtoJSON(s.WithField("content", true))
		case "created_at", "createdAt":
			if s.ReadNil() {
				x.CreatedAt = nil
				return
			}
			x.CreatedAt = &timestamppb.Timestamp{}
			x.CreatedAt.UnmarshalProtoJSON(s.WithField("created_at", true))
		case "reply_to_key", "replyToKey":
			s.AddField("reply_to_key")
			x.ReplyToKey = s.ReadString()
		case "index":
			s.AddField("index")
			x.Index = s.ReadUint64()
		case "person_peer_id", "personPeerId":
			s.AddField("person_peer_id")
			x.PersonPeerId = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the ChatMessage from JSON.
func (x *ChatMessage) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ChatMessagePage message to JSON.
func (x *ChatMessagePage) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.MessageKeys) > 0 || s.HasField("messageKeys") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("messageKeys")
		s.WriteStringArray(x.MessageKeys)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ChatMessagePage to JSON.
func (x *ChatMessagePage) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ChatMessagePage message from JSON.
func (x *ChatMessagePage) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "message_keys", "messageKeys":
			s.AddField("message_keys")
			if s.ReadNil() {
				x.MessageKeys = nil
				return
			}
			x.MessageKeys = s.ReadStringArray()
		}
	})
}

// UnmarshalJSON unmarshals the ChatMessagePage from JSON.
func (x *ChatMessagePage) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the InitChatDemoOp message to JSON.
func (x *InitChatDemoOp) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.ChannelObjectKey != "" || s.HasField("channelObjectKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("channelObjectKey")
		s.WriteString(x.ChannelObjectKey)
	}
	if x.Timestamp != nil || s.HasField("timestamp") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timestamp")
		x.Timestamp.MarshalProtoJSON(s.WithField("timestamp"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the InitChatDemoOp to JSON.
func (x *InitChatDemoOp) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the InitChatDemoOp message from JSON.
func (x *InitChatDemoOp) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "channel_object_key", "channelObjectKey":
			s.AddField("channel_object_key")
			x.ChannelObjectKey = s.ReadString()
		case "timestamp":
			if s.ReadNil() {
				x.Timestamp = nil
				return
			}
			x.Timestamp = &timestamppb.Timestamp{}
			x.Timestamp.UnmarshalProtoJSON(s.WithField("timestamp", true))
		}
	})
}

// UnmarshalJSON unmarshals the InitChatDemoOp from JSON.
func (x *InitChatDemoOp) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the CreateChatChannelOp message to JSON.
func (x *CreateChatChannelOp) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.ObjectKey != "" || s.HasField("objectKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("objectKey")
		s.WriteString(x.ObjectKey)
	}
	if x.Name != "" || s.HasField("name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteString(x.Name)
	}
	if x.Topic != "" || s.HasField("topic") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("topic")
		s.WriteString(x.Topic)
	}
	if x.Timestamp != nil || s.HasField("timestamp") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timestamp")
		x.Timestamp.MarshalProtoJSON(s.WithField("timestamp"))
	}
	if x.EncryptionAlgorithm != "" || s.HasField("encryptionAlgorithm") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("encryptionAlgorithm")
		s.WriteString(x.EncryptionAlgorithm)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CreateChatChannelOp to JSON.
func (x *CreateChatChannelOp) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CreateChatChannelOp message from JSON.
func (x *CreateChatChannelOp) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "object_key", "objectKey":
			s.AddField("object_key")
			x.ObjectKey = s.ReadString()
		case "name":
			s.AddField("name")
			x.Name = s.ReadString()
		case "topic":
			s.AddField("topic")
			x.Topic = s.ReadString()
		case "timestamp":
			if s.ReadNil() {
				x.Timestamp = nil
				return
			}
			x.Timestamp = &timestamppb.Timestamp{}
			x.Timestamp.UnmarshalProtoJSON(s.WithField("timestamp", true))
		case "encryption_algorithm", "encryptionAlgorithm":
			s.AddField("encryption_algorithm")
			x.EncryptionAlgorithm = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the CreateChatChannelOp from JSON.
func (x *CreateChatChannelOp) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *ChatChannel) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChatChannel) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ChatChannel) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.EncryptionAlgorithm) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.EncryptionAlgorithm)
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CreatorPeerId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.CreatorPeerId)
		i--
		dAtA[i] = 0x32
	}
	if len(m.ReadPositions) > 0 {
		for k := range m.ReadPositions {
			v := m.ReadPositions[k]
			baseI := i
			size, err := v.MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i = protobuf_go_lite.EncodeString(dAtA, i, k)
			i--
			dAtA[i] = 0xa
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.MessageCount != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.MessageCount))
		i--
		dAtA[i] = 0x20
	}
	if m.CreatedAt != nil {
		size, err := m.CreatedAt.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Topic) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Topic)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Name)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChatMessage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChatMessage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ChatMessage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.PersonPeerId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.PersonPeerId)
		i--
		dAtA[i] = 0x32
	}
	if m.Index != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ReplyToKey) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ReplyToKey)
		i--
		dAtA[i] = 0x22
	}
	if m.CreatedAt != nil {
		size, err := m.CreatedAt.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Content != nil {
		size, err := m.Content.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SenderPeerId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.SenderPeerId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChatMessagePage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChatMessagePage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ChatMessagePage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.MessageKeys) > 0 {
		for iNdEx := len(m.MessageKeys) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.MessageKeys[iNdEx])
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *InitChatDemoOp) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitChatDemoOp) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *InitChatDemoOp) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Timestamp != nil {
		size, err := m.Timestamp.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChannelObjectKey) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ChannelObjectKey)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateChatChannelOp) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateChatChannelOp) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CreateChatChannelOp) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.EncryptionAlgorithm) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.EncryptionAlgorithm)
		i--
		dAtA[i] = 0x2a
	}
	if m.Timestamp != nil {
		size, err := m.Timestamp.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Topic) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Topic)
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Name)
		i--
		dAtA[i] = 0x12
	}
	if len(m.ObjectKey) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ObjectKey)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChatChannel) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Name)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Topic)
	if m.CreatedAt != nil {
		l = m.CreatedAt.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeVarintNonZero(1, m.MessageCount)
	for k, v := range m.ReadPositions {
		_ = k
		_ = v
		l = 0
		if v != nil {
			l = v.SizeVT()
		}
		mapEntrySize := protobuf_go_lite.SizeStringValue(1, k) + protobuf_go_lite.SizeMessage(1, l)
		n += protobuf_go_lite.SizeMessage(1, mapEntrySize)
	}
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.CreatorPeerId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.EncryptionAlgorithm)
	n += len(m.unknownFields)
	return n
}

func (m *ChatMessage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.SenderPeerId)
	if m.Content != nil {
		l = m.Content.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.CreatedAt != nil {
		l = m.CreatedAt.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ReplyToKey)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Index)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.PersonPeerId)
	n += len(m.unknownFields)
	return n
}

func (m *ChatMessagePage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringSlice(1, m.MessageKeys)
	n += len(m.unknownFields)
	return n
}

func (m *InitChatDemoOp) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ChannelObjectKey)
	if m.Timestamp != nil {
		l = m.Timestamp.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *CreateChatChannelOp) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ObjectKey)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Name)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Topic)
	if m.Timestamp != nil {
		l = m.Timestamp.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.EncryptionAlgorithm)
	n += len(m.unknownFields)
	return n
}

func (x *ChatChannel_ReadPositionsEntry) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ReadPositionsEntry")
	if x.Key != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "key")
		protobuf_go_lite.TextWriteString(&sb, x.Key)
	}
	if x.Value != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "value")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Value)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ChatChannel_ReadPositionsEntry) String() string {
	return x.MarshalProtoText()
}

func (x *ChatChannel) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ChatChannel")
	if x.Name != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "name")
		protobuf_go_lite.TextWriteString(&sb, x.Name)
	}
	if x.Topic != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "topic")
		protobuf_go_lite.TextWriteString(&sb, x.Topic)
	}
	if x.CreatedAt != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "created_at")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.CreatedAt)
	}
	if x.MessageCount != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "message_count")
		protobuf_go_lite.TextWriteUint(&sb, x.MessageCount)
	}
	if len(x.ReadPositions) > 0 {
		protobuf_go_lite.TextWriteMapStart(&sb, initialLen, "read_positions")
		for _, k := range protobuf_go_lite.TextSortedMapKeys(x.ReadPositions) {
			v := x.ReadPositions[k]
			protobuf_go_lite.TextWriteMapEntryPrefix(&sb)
			protobuf_go_lite.TextWriteString(&sb, k)
			protobuf_go_lite.TextWriteMapKeyValueSeparator(&sb)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &state.ChatReadPosition{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteMapEnd(&sb)
	}
	if x.CreatorPeerId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "creator_peer_id")
		protobuf_go_lite.TextWriteString(&sb, x.CreatorPeerId)
	}
	if x.EncryptionAlgorithm != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "encryption_algorithm")
		protobuf_go_lite.TextWriteString(&sb, x.EncryptionAlgorithm)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ChatChannel) String() string {
	return x.MarshalProtoText()
}

func (x *ChatMessage) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ChatMessage")
	if x.SenderPeerId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "sender_peer_id")
		protobuf_go_lite.TextWriteString(&sb, x.SenderPeerId)
	}
	if x.Content != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "content")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Content)
	}
	if x.CreatedAt != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "created_at")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.CreatedAt)
	}
	if x.ReplyToKey != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "reply_to_key")
		protobuf_go_lite.TextWriteString(&sb, x.ReplyToKey)
	}
	if x.Index != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "index")
		protobuf_go_lite.TextWriteUint(&sb, x.Index)
	}
	if x.PersonPeerId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "person_peer_id")
		protobuf_go_lite.TextWriteString(&sb, x.PersonPeerId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ChatMessage) String() string {
	return x.MarshalProtoText()
}

func (x *ChatMessagePage) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ChatMessagePage")
	if len(x.MessageKeys) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "message_keys")
		for i, v := range x.MessageKeys {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ChatMessagePage) String() string {
	return x.MarshalProtoText()
}

func (x *InitChatDemoOp) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "InitChatDemoOp")
	if x.ChannelObjectKey != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "channel_object_key")
		protobuf_go_lite.TextWriteString(&sb, x.ChannelObjectKey)
	}
	if x.Timestamp != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Timestamp)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *InitChatDemoOp) String() string {
	return x.MarshalProtoText()
}

func (x *CreateChatChannelOp) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CreateChatChannelOp")
	if x.ObjectKey != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "object_key")
		protobuf_go_lite.TextWriteString(&sb, x.ObjectKey)
	}
	if x.Name != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "name")
		protobuf_go_lite.TextWriteString(&sb, x.Name)
	}
	if x.Topic != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "topic")
		protobuf_go_lite.TextWriteString(&sb, x.Topic)
	}
	if x.Timestamp != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Timestamp)
	}
	if x.EncryptionAlgorithm != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "encryption_algorithm")
		protobuf_go_lite.TextWriteString(&sb, x.EncryptionAlgorithm)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CreateChatChannelOp) String() string {
	return x.MarshalProtoText()
}

func (m *ChatChannel) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChatChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChatChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Name = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Topic = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &timestamppb.Timestamp{}
			}
			if err := m.CreatedAt.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageCount", wireType)
			}
			m.MessageCount = 0
			m.MessageCount, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadPositions", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			iNdEx = msgStart
			if m.ReadPositions == nil {
				m.ReadPositions = make(map[string]*state.ChatReadPosition)
			}
			var mapkey string
			var mapvalue *state.ChatReadPosition
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
				if err != nil {
					return err
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					mapkey, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
					if err != nil {
						return err
					}
				} else if fieldNum == 2 {
					msgStartmapvalue, postmsgIndexmapvalue, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
					if err != nil {
						return err
					}
					mapvalue = &state.ChatReadPosition{}
					if err := mapvalue.UnmarshalVT(dAtA[msgStartmapvalue:postmsgIndexmapvalue]); err != nil {
						return err
					}
					iNdEx = postmsgIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					iNdEx, err = protobuf_go_lite.SkipWithin(dAtA, iNdEx, postIndex)
					if err != nil {
						return err
					}
				}
			}
			m.ReadPositions[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorPeerId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CreatorPeerId = v
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptionAlgorithm", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.EncryptionAlgorithm = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ChatMessage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChatMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChatMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderPeerId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SenderPeerId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Content == nil {
				m.Content = &content.ChatMessageContent{}
			}
			if err := m.Content.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &timestamppb.Timestamp{}
			}
			if err := m.CreatedAt.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplyToKey", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ReplyToKey = v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			m.Index, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PersonPeerId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.PersonPeerId = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ChatMessagePage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChatMessagePage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChatMessagePage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageKeys", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.MessageKeys = append(m.MessageKeys, v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *InitChatDemoOp) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitChatDemoOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitChatDemoOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelObjectKey", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ChannelObjectKey = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Timestamp == nil {
				m.Timestamp = &timestamppb.Timestamp{}
			}
			if err := m.Timestamp.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CreateChatChannelOp) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateChatChannelOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateChatChannelOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectKey", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ObjectKey = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Name = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Topic = v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Timestamp == nil {
				m.Timestamp = &timestamppb.Timestamp{}
			}
			if err := m.Timestamp.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptionAlgorithm", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.EncryptionAlgorithm = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
