// @generated by protoc-gen-es-starpc none with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/s4wave/spacewave/bldr/frontend/frontend.proto (package bldr.frontend, syntax proto3)
/* eslint-disable */

import {
  Event,
  SendRequest,
  SendResponse,
  WatchRequest,
} from './frontend.pb.js'
import { MethodKind } from '@aptre/protobuf-es-lite'
import { FetchRequest, FetchResponse } from '../web/fetch/fetch.pb.js'
import {
  buildDecodeMessageTransform,
  buildEncodeMessageTransform,
  MessageStream,
  ProtoRpc,
  ServerContext,
} from 'starpc'

/**
 * Frontend serves the active project's live modules and compiler updates.
 * Browser clients reach it through the existing devtool RPC connection.
 *
 * @generated from service bldr.frontend.Frontend
 */
export const FrontendDefinition = {
  typeName: 'bldr.frontend.Frontend',
  methods: {
    /**
     * Watch starts with the current session and sequence, then streams updates.
     * A new session or a sequence gap requires reloading the document.
     *
     * @generated from rpc bldr.frontend.Frontend.Watch
     */
    Watch: {
      name: 'Watch',
      I: WatchRequest,
      O: Event,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Send delivers a client HMR message to the selected compiler session.
     *
     * @generated from rpc bldr.frontend.Frontend.Send
     */
    Send: {
      name: 'Send',
      I: SendRequest,
      O: SendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Fetch serves modules from the session named by the request URL.
     *
     * @generated from rpc bldr.frontend.Frontend.Fetch
     */
    Fetch: {
      name: 'Fetch',
      I: FetchRequest,
      O: FetchResponse,
      kind: MethodKind.BiDiStreaming,
    },
  },
} as const

/**
 * Frontend serves the active project's live modules and compiler updates.
 * Browser clients reach it through the existing devtool RPC connection.
 *
 * @generated from service bldr.frontend.Frontend
 */
export interface Frontend {
  /**
   * Watch starts with the current session and sequence, then streams updates.
   * A new session or a sequence gap requires reloading the document.
   *
   * @generated from rpc bldr.frontend.Frontend.Watch
   */
  Watch(request: WatchRequest, abortSignal?: AbortSignal): MessageStream<Event>

  /**
   * Send delivers a client HMR message to the selected compiler session.
   *
   * @generated from rpc bldr.frontend.Frontend.Send
   */
  Send(request: SendRequest, abortSignal?: AbortSignal): Promise<SendResponse>

  /**
   * Fetch serves modules from the session named by the request URL.
   *
   * @generated from rpc bldr.frontend.Frontend.Fetch
   */
  Fetch(
    request: MessageStream<FetchRequest>,
    abortSignal?: AbortSignal,
  ): MessageStream<FetchResponse>
}

/**
 * Frontend serves the active project's live modules and compiler updates.
 * Browser clients reach it through the existing devtool RPC connection.
 *
 * @generated from service bldr.frontend.Frontend
 */
export interface FrontendHandler {
  /**
   * Watch starts with the current session and sequence, then streams updates.
   * A new session or a sequence gap requires reloading the document.
   *
   * @generated from rpc bldr.frontend.Frontend.Watch
   */
  Watch(
    request: WatchRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<Event>

  /**
   * Send delivers a client HMR message to the selected compiler session.
   *
   * @generated from rpc bldr.frontend.Frontend.Send
   */
  Send(
    request: SendRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<SendResponse>

  /**
   * Fetch serves modules from the session named by the request URL.
   *
   * @generated from rpc bldr.frontend.Frontend.Fetch
   */
  Fetch(
    request: MessageStream<FetchRequest>,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<FetchResponse>
}

export const FrontendServiceName = FrontendDefinition.typeName

export class FrontendClient implements Frontend {
  private readonly rpc: ProtoRpc
  private readonly service: string
  constructor(rpc: ProtoRpc, opts?: { service?: string }) {
    this.service = opts?.service || FrontendServiceName
    this.rpc = rpc
    this.Watch = this.Watch.bind(this)
    this.Send = this.Send.bind(this)
    this.Fetch = this.Fetch.bind(this)
  }
  /**
   * Watch starts with the current session and sequence, then streams updates.
   * A new session or a sequence gap requires reloading the document.
   *
   * @generated from rpc bldr.frontend.Frontend.Watch
   */
  Watch(
    request: WatchRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<Event> {
    const requestMsg = WatchRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      FrontendDefinition.methods.Watch.name,
      WatchRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(Event)(result)
  }

  /**
   * Send delivers a client HMR message to the selected compiler session.
   *
   * @generated from rpc bldr.frontend.Frontend.Send
   */
  async Send(
    request: SendRequest,
    abortSignal?: AbortSignal,
  ): Promise<SendResponse> {
    const requestMsg = SendRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      FrontendDefinition.methods.Send.name,
      SendRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return SendResponse.fromBinary(result)
  }

  /**
   * Fetch serves modules from the session named by the request URL.
   *
   * @generated from rpc bldr.frontend.Frontend.Fetch
   */
  Fetch(
    request: MessageStream<FetchRequest>,
    abortSignal?: AbortSignal,
  ): MessageStream<FetchResponse> {
    const result = this.rpc.bidirectionalStreamingRequest(
      this.service,
      FrontendDefinition.methods.Fetch.name,
      buildEncodeMessageTransform(FetchRequest)(request),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(FetchResponse)(result)
  }
}
