// @generated by protoc-gen-es-starpc none with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/s4wave/spacewave/sdk/root/root.proto (package s4wave.root, syntax proto3)
/* eslint-disable */

import {
  AccessStateAtomRequest,
  AccessStateAtomResponse,
  AccessWebListenerRequest,
  AccessWebListenerResponse,
  DeleteSessionRequest,
  DeleteSessionResponse,
  GetCdnRequest,
  GetCdnResponse,
  GetChangelogRequest,
  GetChangelogResponse,
  GetDebugDbRequest,
  GetDebugDbResponse,
  GetSessionMetadataRequest,
  GetSessionMetadataResponse,
  HashSumRequest,
  HashSumResponse,
  HashValidateRequest,
  HashValidateResponse,
  ListProvidersRequest,
  ListProvidersResponse,
  ListSessionsRequest,
  ListSessionsResponse,
  ListSpaceRootAliasesRequest,
  ListSpaceRootAliasesResponse,
  LookupProviderRequest,
  LookupProviderResponse,
  MarshalHashRequest,
  MarshalHashResponse,
  MountAppRequest,
  MountAppResponse,
  MountSessionByIdxRequest,
  MountSessionByIdxResponse,
  MountSessionRequest,
  MountSessionResponse,
  ParseHashRequest,
  ParseHashResponse,
  ReclaimRuntimeRequest,
  ReclaimRuntimeResponse,
  RemoveSpaceRootAliasRequest,
  RemoveSpaceRootAliasResponse,
  ResetSessionByIdxRequest,
  ResetSessionByIdxResponse,
  RespondToListenerYieldPromptRequest,
  RespondToListenerYieldPromptResponse,
  StopWebListenerRequest,
  StopWebListenerResponse,
  UnlockSessionByIdxRequest,
  UnlockSessionByIdxResponse,
  UpsertSpaceRootAliasRequest,
  UpsertSpaceRootAliasResponse,
  WatchAllAccountStatusesRequest,
  WatchAllAccountStatusesResponse,
  WatchListenerStatusRequest,
  WatchListenerStatusResponse,
  WatchListenerYieldPromptsRequest,
  WatchListenerYieldPromptsResponse,
  WatchRuntimeHandoffRequest,
  WatchRuntimeHandoffResponse,
  WatchSessionMetadataRequest,
  WatchSessionMetadataResponse,
  WatchSessionsRequest,
  WatchSessionsResponse,
  WatchSpaceRootAliasesRequest,
  WatchSpaceRootAliasesResponse,
  WatchSpaceRootRuntimeRequest,
  WatchSpaceRootRuntimeResponse,
  WatchStateAtomsRequest,
  WatchStateAtomsResponse,
  WatchWebListenersRequest,
  WatchWebListenersResponse,
} from './root.pb.js'
import { MethodKind } from '@aptre/protobuf-es-lite'
import {
  buildDecodeMessageTransform,
  MessageStream,
  ProtoRpc,
  ServerContext,
} from 'starpc'

/**
 * @generated from service s4wave.root.RootResourceService
 */
export const RootResourceServiceDefinition = {
  typeName: 's4wave.root.RootResourceService',
  methods: {
    /**
     * @generated from rpc s4wave.root.RootResourceService.MountApp
     */
    MountApp: {
      name: 'MountApp',
      I: MountAppRequest,
      O: MountAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.ListProviders
     */
    ListProviders: {
      name: 'ListProviders',
      I: ListProvidersRequest,
      O: ListProvidersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.LookupProvider
     */
    LookupProvider: {
      name: 'LookupProvider',
      I: LookupProviderRequest,
      O: LookupProviderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.MountSession
     */
    MountSession: {
      name: 'MountSession',
      I: MountSessionRequest,
      O: MountSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.MountSessionByIdx
     */
    MountSessionByIdx: {
      name: 'MountSessionByIdx',
      I: MountSessionByIdxRequest,
      O: MountSessionByIdxResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.ListSessions
     */
    ListSessions: {
      name: 'ListSessions',
      I: ListSessionsRequest,
      O: ListSessionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchSessions
     */
    WatchSessions: {
      name: 'WatchSessions',
      I: WatchSessionsRequest,
      O: WatchSessionsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchAllAccountStatuses
     */
    WatchAllAccountStatuses: {
      name: 'WatchAllAccountStatuses',
      I: WatchAllAccountStatusesRequest,
      O: WatchAllAccountStatusesResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.GetSessionMetadata
     */
    GetSessionMetadata: {
      name: 'GetSessionMetadata',
      I: GetSessionMetadataRequest,
      O: GetSessionMetadataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchSessionMetadata
     */
    WatchSessionMetadata: {
      name: 'WatchSessionMetadata',
      I: WatchSessionMetadataRequest,
      O: WatchSessionMetadataResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.UnlockSession
     */
    UnlockSession: {
      name: 'UnlockSession',
      I: UnlockSessionByIdxRequest,
      O: UnlockSessionByIdxResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.DeleteSession
     */
    DeleteSession: {
      name: 'DeleteSession',
      I: DeleteSessionRequest,
      O: DeleteSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.ResetSession
     */
    ResetSession: {
      name: 'ResetSession',
      I: ResetSessionByIdxRequest,
      O: ResetSessionByIdxResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.AccessStateAtom
     */
    AccessStateAtom: {
      name: 'AccessStateAtom',
      I: AccessStateAtomRequest,
      O: AccessStateAtomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchStateAtoms
     */
    WatchStateAtoms: {
      name: 'WatchStateAtoms',
      I: WatchStateAtomsRequest,
      O: WatchStateAtomsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.ListSpaceRootAliases
     */
    ListSpaceRootAliases: {
      name: 'ListSpaceRootAliases',
      I: ListSpaceRootAliasesRequest,
      O: ListSpaceRootAliasesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootAliases
     */
    WatchSpaceRootAliases: {
      name: 'WatchSpaceRootAliases',
      I: WatchSpaceRootAliasesRequest,
      O: WatchSpaceRootAliasesResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.UpsertSpaceRootAlias
     */
    UpsertSpaceRootAlias: {
      name: 'UpsertSpaceRootAlias',
      I: UpsertSpaceRootAliasRequest,
      O: UpsertSpaceRootAliasResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.RemoveSpaceRootAlias
     */
    RemoveSpaceRootAlias: {
      name: 'RemoveSpaceRootAlias',
      I: RemoveSpaceRootAliasRequest,
      O: RemoveSpaceRootAliasResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootRuntime
     */
    WatchSpaceRootRuntime: {
      name: 'WatchSpaceRootRuntime',
      I: WatchSpaceRootRuntimeRequest,
      O: WatchSpaceRootRuntimeResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.MarshalHash
     */
    MarshalHash: {
      name: 'MarshalHash',
      I: MarshalHashRequest,
      O: MarshalHashResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.ParseHash
     */
    ParseHash: {
      name: 'ParseHash',
      I: ParseHashRequest,
      O: ParseHashResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.HashSum
     */
    HashSum: {
      name: 'HashSum',
      I: HashSumRequest,
      O: HashSumResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.HashValidate
     */
    HashValidate: {
      name: 'HashValidate',
      I: HashValidateRequest,
      O: HashValidateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.GetChangelog
     */
    GetChangelog: {
      name: 'GetChangelog',
      I: GetChangelogRequest,
      O: GetChangelogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.GetDebugDb
     */
    GetDebugDb: {
      name: 'GetDebugDb',
      I: GetDebugDbRequest,
      O: GetDebugDbResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.GetCdn
     */
    GetCdn: {
      name: 'GetCdn',
      I: GetCdnRequest,
      O: GetCdnResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.AccessWebListener
     */
    AccessWebListener: {
      name: 'AccessWebListener',
      I: AccessWebListenerRequest,
      O: AccessWebListenerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchWebListeners
     */
    WatchWebListeners: {
      name: 'WatchWebListeners',
      I: WatchWebListenersRequest,
      O: WatchWebListenersResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.StopWebListener
     */
    StopWebListener: {
      name: 'StopWebListener',
      I: StopWebListenerRequest,
      O: StopWebListenerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchListenerYieldPrompts
     */
    WatchListenerYieldPrompts: {
      name: 'WatchListenerYieldPrompts',
      I: WatchListenerYieldPromptsRequest,
      O: WatchListenerYieldPromptsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.RespondToListenerYieldPrompt
     */
    RespondToListenerYieldPrompt: {
      name: 'RespondToListenerYieldPrompt',
      I: RespondToListenerYieldPromptRequest,
      O: RespondToListenerYieldPromptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchRuntimeHandoff
     */
    WatchRuntimeHandoff: {
      name: 'WatchRuntimeHandoff',
      I: WatchRuntimeHandoffRequest,
      O: WatchRuntimeHandoffResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.ReclaimRuntime
     */
    ReclaimRuntime: {
      name: 'ReclaimRuntime',
      I: ReclaimRuntimeRequest,
      O: ReclaimRuntimeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc s4wave.root.RootResourceService.WatchListenerStatus
     */
    WatchListenerStatus: {
      name: 'WatchListenerStatus',
      I: WatchListenerStatusRequest,
      O: WatchListenerStatusResponse,
      kind: MethodKind.ServerStreaming,
    },
  },
} as const

/**
 * @generated from service s4wave.root.RootResourceService
 */
export interface RootResourceService {
  /**
   * @generated from rpc s4wave.root.RootResourceService.MountApp
   */
  MountApp(
    request: MountAppRequest,
    abortSignal?: AbortSignal,
  ): Promise<MountAppResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListProviders
   */
  ListProviders(
    request: ListProvidersRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListProvidersResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.LookupProvider
   */
  LookupProvider(
    request: LookupProviderRequest,
    abortSignal?: AbortSignal,
  ): Promise<LookupProviderResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.MountSession
   */
  MountSession(
    request: MountSessionRequest,
    abortSignal?: AbortSignal,
  ): Promise<MountSessionResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.MountSessionByIdx
   */
  MountSessionByIdx(
    request: MountSessionByIdxRequest,
    abortSignal?: AbortSignal,
  ): Promise<MountSessionByIdxResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListSessions
   */
  ListSessions(
    request: ListSessionsRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListSessionsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSessions
   */
  WatchSessions(
    request: WatchSessionsRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSessionsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchAllAccountStatuses
   */
  WatchAllAccountStatuses(
    request: WatchAllAccountStatusesRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchAllAccountStatusesResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetSessionMetadata
   */
  GetSessionMetadata(
    request: GetSessionMetadataRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetSessionMetadataResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSessionMetadata
   */
  WatchSessionMetadata(
    request: WatchSessionMetadataRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSessionMetadataResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.UnlockSession
   */
  UnlockSession(
    request: UnlockSessionByIdxRequest,
    abortSignal?: AbortSignal,
  ): Promise<UnlockSessionByIdxResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.DeleteSession
   */
  DeleteSession(
    request: DeleteSessionRequest,
    abortSignal?: AbortSignal,
  ): Promise<DeleteSessionResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ResetSession
   */
  ResetSession(
    request: ResetSessionByIdxRequest,
    abortSignal?: AbortSignal,
  ): Promise<ResetSessionByIdxResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.AccessStateAtom
   */
  AccessStateAtom(
    request: AccessStateAtomRequest,
    abortSignal?: AbortSignal,
  ): Promise<AccessStateAtomResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchStateAtoms
   */
  WatchStateAtoms(
    request: WatchStateAtomsRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchStateAtomsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListSpaceRootAliases
   */
  ListSpaceRootAliases(
    request: ListSpaceRootAliasesRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListSpaceRootAliasesResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootAliases
   */
  WatchSpaceRootAliases(
    request: WatchSpaceRootAliasesRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSpaceRootAliasesResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.UpsertSpaceRootAlias
   */
  UpsertSpaceRootAlias(
    request: UpsertSpaceRootAliasRequest,
    abortSignal?: AbortSignal,
  ): Promise<UpsertSpaceRootAliasResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.RemoveSpaceRootAlias
   */
  RemoveSpaceRootAlias(
    request: RemoveSpaceRootAliasRequest,
    abortSignal?: AbortSignal,
  ): Promise<RemoveSpaceRootAliasResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootRuntime
   */
  WatchSpaceRootRuntime(
    request: WatchSpaceRootRuntimeRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSpaceRootRuntimeResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.MarshalHash
   */
  MarshalHash(
    request: MarshalHashRequest,
    abortSignal?: AbortSignal,
  ): Promise<MarshalHashResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ParseHash
   */
  ParseHash(
    request: ParseHashRequest,
    abortSignal?: AbortSignal,
  ): Promise<ParseHashResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.HashSum
   */
  HashSum(
    request: HashSumRequest,
    abortSignal?: AbortSignal,
  ): Promise<HashSumResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.HashValidate
   */
  HashValidate(
    request: HashValidateRequest,
    abortSignal?: AbortSignal,
  ): Promise<HashValidateResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetChangelog
   */
  GetChangelog(
    request: GetChangelogRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetChangelogResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetDebugDb
   */
  GetDebugDb(
    request: GetDebugDbRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetDebugDbResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetCdn
   */
  GetCdn(
    request: GetCdnRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetCdnResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.AccessWebListener
   */
  AccessWebListener(
    request: AccessWebListenerRequest,
    abortSignal?: AbortSignal,
  ): Promise<AccessWebListenerResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchWebListeners
   */
  WatchWebListeners(
    request: WatchWebListenersRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchWebListenersResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.StopWebListener
   */
  StopWebListener(
    request: StopWebListenerRequest,
    abortSignal?: AbortSignal,
  ): Promise<StopWebListenerResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchListenerYieldPrompts
   */
  WatchListenerYieldPrompts(
    request: WatchListenerYieldPromptsRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchListenerYieldPromptsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.RespondToListenerYieldPrompt
   */
  RespondToListenerYieldPrompt(
    request: RespondToListenerYieldPromptRequest,
    abortSignal?: AbortSignal,
  ): Promise<RespondToListenerYieldPromptResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchRuntimeHandoff
   */
  WatchRuntimeHandoff(
    request: WatchRuntimeHandoffRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchRuntimeHandoffResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ReclaimRuntime
   */
  ReclaimRuntime(
    request: ReclaimRuntimeRequest,
    abortSignal?: AbortSignal,
  ): Promise<ReclaimRuntimeResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchListenerStatus
   */
  WatchListenerStatus(
    request: WatchListenerStatusRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchListenerStatusResponse>
}

/**
 * @generated from service s4wave.root.RootResourceService
 */
export interface RootResourceServiceHandler {
  /**
   * @generated from rpc s4wave.root.RootResourceService.MountApp
   */
  MountApp(
    request: MountAppRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<MountAppResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListProviders
   */
  ListProviders(
    request: ListProvidersRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ListProvidersResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.LookupProvider
   */
  LookupProvider(
    request: LookupProviderRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<LookupProviderResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.MountSession
   */
  MountSession(
    request: MountSessionRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<MountSessionResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.MountSessionByIdx
   */
  MountSessionByIdx(
    request: MountSessionByIdxRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<MountSessionByIdxResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListSessions
   */
  ListSessions(
    request: ListSessionsRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ListSessionsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSessions
   */
  WatchSessions(
    request: WatchSessionsRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchSessionsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchAllAccountStatuses
   */
  WatchAllAccountStatuses(
    request: WatchAllAccountStatusesRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchAllAccountStatusesResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetSessionMetadata
   */
  GetSessionMetadata(
    request: GetSessionMetadataRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<GetSessionMetadataResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSessionMetadata
   */
  WatchSessionMetadata(
    request: WatchSessionMetadataRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchSessionMetadataResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.UnlockSession
   */
  UnlockSession(
    request: UnlockSessionByIdxRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<UnlockSessionByIdxResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.DeleteSession
   */
  DeleteSession(
    request: DeleteSessionRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<DeleteSessionResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ResetSession
   */
  ResetSession(
    request: ResetSessionByIdxRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ResetSessionByIdxResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.AccessStateAtom
   */
  AccessStateAtom(
    request: AccessStateAtomRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<AccessStateAtomResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchStateAtoms
   */
  WatchStateAtoms(
    request: WatchStateAtomsRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchStateAtomsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListSpaceRootAliases
   */
  ListSpaceRootAliases(
    request: ListSpaceRootAliasesRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ListSpaceRootAliasesResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootAliases
   */
  WatchSpaceRootAliases(
    request: WatchSpaceRootAliasesRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchSpaceRootAliasesResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.UpsertSpaceRootAlias
   */
  UpsertSpaceRootAlias(
    request: UpsertSpaceRootAliasRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<UpsertSpaceRootAliasResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.RemoveSpaceRootAlias
   */
  RemoveSpaceRootAlias(
    request: RemoveSpaceRootAliasRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<RemoveSpaceRootAliasResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootRuntime
   */
  WatchSpaceRootRuntime(
    request: WatchSpaceRootRuntimeRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchSpaceRootRuntimeResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.MarshalHash
   */
  MarshalHash(
    request: MarshalHashRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<MarshalHashResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ParseHash
   */
  ParseHash(
    request: ParseHashRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ParseHashResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.HashSum
   */
  HashSum(
    request: HashSumRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<HashSumResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.HashValidate
   */
  HashValidate(
    request: HashValidateRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<HashValidateResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetChangelog
   */
  GetChangelog(
    request: GetChangelogRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<GetChangelogResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetDebugDb
   */
  GetDebugDb(
    request: GetDebugDbRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<GetDebugDbResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetCdn
   */
  GetCdn(
    request: GetCdnRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<GetCdnResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.AccessWebListener
   */
  AccessWebListener(
    request: AccessWebListenerRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<AccessWebListenerResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchWebListeners
   */
  WatchWebListeners(
    request: WatchWebListenersRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchWebListenersResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.StopWebListener
   */
  StopWebListener(
    request: StopWebListenerRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<StopWebListenerResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchListenerYieldPrompts
   */
  WatchListenerYieldPrompts(
    request: WatchListenerYieldPromptsRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchListenerYieldPromptsResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.RespondToListenerYieldPrompt
   */
  RespondToListenerYieldPrompt(
    request: RespondToListenerYieldPromptRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<RespondToListenerYieldPromptResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchRuntimeHandoff
   */
  WatchRuntimeHandoff(
    request: WatchRuntimeHandoffRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchRuntimeHandoffResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.ReclaimRuntime
   */
  ReclaimRuntime(
    request: ReclaimRuntimeRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): Promise<ReclaimRuntimeResponse>

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchListenerStatus
   */
  WatchListenerStatus(
    request: WatchListenerStatusRequest,
    abortSignal: AbortSignal,
    context: ServerContext,
  ): MessageStream<WatchListenerStatusResponse>
}

export const RootResourceServiceServiceName =
  RootResourceServiceDefinition.typeName

export class RootResourceServiceClient implements RootResourceService {
  private readonly rpc: ProtoRpc
  private readonly service: string
  constructor(rpc: ProtoRpc, opts?: { service?: string }) {
    this.service = opts?.service || RootResourceServiceServiceName
    this.rpc = rpc
    this.MountApp = this.MountApp.bind(this)
    this.ListProviders = this.ListProviders.bind(this)
    this.LookupProvider = this.LookupProvider.bind(this)
    this.MountSession = this.MountSession.bind(this)
    this.MountSessionByIdx = this.MountSessionByIdx.bind(this)
    this.ListSessions = this.ListSessions.bind(this)
    this.WatchSessions = this.WatchSessions.bind(this)
    this.WatchAllAccountStatuses = this.WatchAllAccountStatuses.bind(this)
    this.GetSessionMetadata = this.GetSessionMetadata.bind(this)
    this.WatchSessionMetadata = this.WatchSessionMetadata.bind(this)
    this.UnlockSession = this.UnlockSession.bind(this)
    this.DeleteSession = this.DeleteSession.bind(this)
    this.ResetSession = this.ResetSession.bind(this)
    this.AccessStateAtom = this.AccessStateAtom.bind(this)
    this.WatchStateAtoms = this.WatchStateAtoms.bind(this)
    this.ListSpaceRootAliases = this.ListSpaceRootAliases.bind(this)
    this.WatchSpaceRootAliases = this.WatchSpaceRootAliases.bind(this)
    this.UpsertSpaceRootAlias = this.UpsertSpaceRootAlias.bind(this)
    this.RemoveSpaceRootAlias = this.RemoveSpaceRootAlias.bind(this)
    this.WatchSpaceRootRuntime = this.WatchSpaceRootRuntime.bind(this)
    this.MarshalHash = this.MarshalHash.bind(this)
    this.ParseHash = this.ParseHash.bind(this)
    this.HashSum = this.HashSum.bind(this)
    this.HashValidate = this.HashValidate.bind(this)
    this.GetChangelog = this.GetChangelog.bind(this)
    this.GetDebugDb = this.GetDebugDb.bind(this)
    this.GetCdn = this.GetCdn.bind(this)
    this.AccessWebListener = this.AccessWebListener.bind(this)
    this.WatchWebListeners = this.WatchWebListeners.bind(this)
    this.StopWebListener = this.StopWebListener.bind(this)
    this.WatchListenerYieldPrompts = this.WatchListenerYieldPrompts.bind(this)
    this.RespondToListenerYieldPrompt =
      this.RespondToListenerYieldPrompt.bind(this)
    this.WatchRuntimeHandoff = this.WatchRuntimeHandoff.bind(this)
    this.ReclaimRuntime = this.ReclaimRuntime.bind(this)
    this.WatchListenerStatus = this.WatchListenerStatus.bind(this)
  }
  /**
   * @generated from rpc s4wave.root.RootResourceService.MountApp
   */
  async MountApp(
    request: MountAppRequest,
    abortSignal?: AbortSignal,
  ): Promise<MountAppResponse> {
    const requestMsg = MountAppRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.MountApp.name,
      MountAppRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return MountAppResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListProviders
   */
  async ListProviders(
    request: ListProvidersRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListProvidersResponse> {
    const requestMsg = ListProvidersRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.ListProviders.name,
      ListProvidersRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ListProvidersResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.LookupProvider
   */
  async LookupProvider(
    request: LookupProviderRequest,
    abortSignal?: AbortSignal,
  ): Promise<LookupProviderResponse> {
    const requestMsg = LookupProviderRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.LookupProvider.name,
      LookupProviderRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return LookupProviderResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.MountSession
   */
  async MountSession(
    request: MountSessionRequest,
    abortSignal?: AbortSignal,
  ): Promise<MountSessionResponse> {
    const requestMsg = MountSessionRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.MountSession.name,
      MountSessionRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return MountSessionResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.MountSessionByIdx
   */
  async MountSessionByIdx(
    request: MountSessionByIdxRequest,
    abortSignal?: AbortSignal,
  ): Promise<MountSessionByIdxResponse> {
    const requestMsg = MountSessionByIdxRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.MountSessionByIdx.name,
      MountSessionByIdxRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return MountSessionByIdxResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListSessions
   */
  async ListSessions(
    request: ListSessionsRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListSessionsResponse> {
    const requestMsg = ListSessionsRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.ListSessions.name,
      ListSessionsRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ListSessionsResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSessions
   */
  WatchSessions(
    request: WatchSessionsRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSessionsResponse> {
    const requestMsg = WatchSessionsRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchSessions.name,
      WatchSessionsRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchSessionsResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchAllAccountStatuses
   */
  WatchAllAccountStatuses(
    request: WatchAllAccountStatusesRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchAllAccountStatusesResponse> {
    const requestMsg = WatchAllAccountStatusesRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchAllAccountStatuses.name,
      WatchAllAccountStatusesRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchAllAccountStatusesResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetSessionMetadata
   */
  async GetSessionMetadata(
    request: GetSessionMetadataRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetSessionMetadataResponse> {
    const requestMsg = GetSessionMetadataRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.GetSessionMetadata.name,
      GetSessionMetadataRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return GetSessionMetadataResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSessionMetadata
   */
  WatchSessionMetadata(
    request: WatchSessionMetadataRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSessionMetadataResponse> {
    const requestMsg = WatchSessionMetadataRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchSessionMetadata.name,
      WatchSessionMetadataRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchSessionMetadataResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.UnlockSession
   */
  async UnlockSession(
    request: UnlockSessionByIdxRequest,
    abortSignal?: AbortSignal,
  ): Promise<UnlockSessionByIdxResponse> {
    const requestMsg = UnlockSessionByIdxRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.UnlockSession.name,
      UnlockSessionByIdxRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return UnlockSessionByIdxResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.DeleteSession
   */
  async DeleteSession(
    request: DeleteSessionRequest,
    abortSignal?: AbortSignal,
  ): Promise<DeleteSessionResponse> {
    const requestMsg = DeleteSessionRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.DeleteSession.name,
      DeleteSessionRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return DeleteSessionResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.ResetSession
   */
  async ResetSession(
    request: ResetSessionByIdxRequest,
    abortSignal?: AbortSignal,
  ): Promise<ResetSessionByIdxResponse> {
    const requestMsg = ResetSessionByIdxRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.ResetSession.name,
      ResetSessionByIdxRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ResetSessionByIdxResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.AccessStateAtom
   */
  async AccessStateAtom(
    request: AccessStateAtomRequest,
    abortSignal?: AbortSignal,
  ): Promise<AccessStateAtomResponse> {
    const requestMsg = AccessStateAtomRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.AccessStateAtom.name,
      AccessStateAtomRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return AccessStateAtomResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchStateAtoms
   */
  WatchStateAtoms(
    request: WatchStateAtomsRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchStateAtomsResponse> {
    const requestMsg = WatchStateAtomsRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchStateAtoms.name,
      WatchStateAtomsRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchStateAtomsResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.ListSpaceRootAliases
   */
  async ListSpaceRootAliases(
    request: ListSpaceRootAliasesRequest,
    abortSignal?: AbortSignal,
  ): Promise<ListSpaceRootAliasesResponse> {
    const requestMsg = ListSpaceRootAliasesRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.ListSpaceRootAliases.name,
      ListSpaceRootAliasesRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ListSpaceRootAliasesResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootAliases
   */
  WatchSpaceRootAliases(
    request: WatchSpaceRootAliasesRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSpaceRootAliasesResponse> {
    const requestMsg = WatchSpaceRootAliasesRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchSpaceRootAliases.name,
      WatchSpaceRootAliasesRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchSpaceRootAliasesResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.UpsertSpaceRootAlias
   */
  async UpsertSpaceRootAlias(
    request: UpsertSpaceRootAliasRequest,
    abortSignal?: AbortSignal,
  ): Promise<UpsertSpaceRootAliasResponse> {
    const requestMsg = UpsertSpaceRootAliasRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.UpsertSpaceRootAlias.name,
      UpsertSpaceRootAliasRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return UpsertSpaceRootAliasResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.RemoveSpaceRootAlias
   */
  async RemoveSpaceRootAlias(
    request: RemoveSpaceRootAliasRequest,
    abortSignal?: AbortSignal,
  ): Promise<RemoveSpaceRootAliasResponse> {
    const requestMsg = RemoveSpaceRootAliasRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.RemoveSpaceRootAlias.name,
      RemoveSpaceRootAliasRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return RemoveSpaceRootAliasResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchSpaceRootRuntime
   */
  WatchSpaceRootRuntime(
    request: WatchSpaceRootRuntimeRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchSpaceRootRuntimeResponse> {
    const requestMsg = WatchSpaceRootRuntimeRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchSpaceRootRuntime.name,
      WatchSpaceRootRuntimeRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchSpaceRootRuntimeResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.MarshalHash
   */
  async MarshalHash(
    request: MarshalHashRequest,
    abortSignal?: AbortSignal,
  ): Promise<MarshalHashResponse> {
    const requestMsg = MarshalHashRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.MarshalHash.name,
      MarshalHashRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return MarshalHashResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.ParseHash
   */
  async ParseHash(
    request: ParseHashRequest,
    abortSignal?: AbortSignal,
  ): Promise<ParseHashResponse> {
    const requestMsg = ParseHashRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.ParseHash.name,
      ParseHashRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ParseHashResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.HashSum
   */
  async HashSum(
    request: HashSumRequest,
    abortSignal?: AbortSignal,
  ): Promise<HashSumResponse> {
    const requestMsg = HashSumRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.HashSum.name,
      HashSumRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return HashSumResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.HashValidate
   */
  async HashValidate(
    request: HashValidateRequest,
    abortSignal?: AbortSignal,
  ): Promise<HashValidateResponse> {
    const requestMsg = HashValidateRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.HashValidate.name,
      HashValidateRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return HashValidateResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetChangelog
   */
  async GetChangelog(
    request: GetChangelogRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetChangelogResponse> {
    const requestMsg = GetChangelogRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.GetChangelog.name,
      GetChangelogRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return GetChangelogResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetDebugDb
   */
  async GetDebugDb(
    request: GetDebugDbRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetDebugDbResponse> {
    const requestMsg = GetDebugDbRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.GetDebugDb.name,
      GetDebugDbRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return GetDebugDbResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.GetCdn
   */
  async GetCdn(
    request: GetCdnRequest,
    abortSignal?: AbortSignal,
  ): Promise<GetCdnResponse> {
    const requestMsg = GetCdnRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.GetCdn.name,
      GetCdnRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return GetCdnResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.AccessWebListener
   */
  async AccessWebListener(
    request: AccessWebListenerRequest,
    abortSignal?: AbortSignal,
  ): Promise<AccessWebListenerResponse> {
    const requestMsg = AccessWebListenerRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.AccessWebListener.name,
      AccessWebListenerRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return AccessWebListenerResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchWebListeners
   */
  WatchWebListeners(
    request: WatchWebListenersRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchWebListenersResponse> {
    const requestMsg = WatchWebListenersRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchWebListeners.name,
      WatchWebListenersRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchWebListenersResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.StopWebListener
   */
  async StopWebListener(
    request: StopWebListenerRequest,
    abortSignal?: AbortSignal,
  ): Promise<StopWebListenerResponse> {
    const requestMsg = StopWebListenerRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.StopWebListener.name,
      StopWebListenerRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return StopWebListenerResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchListenerYieldPrompts
   */
  WatchListenerYieldPrompts(
    request: WatchListenerYieldPromptsRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchListenerYieldPromptsResponse> {
    const requestMsg = WatchListenerYieldPromptsRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchListenerYieldPrompts.name,
      WatchListenerYieldPromptsRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchListenerYieldPromptsResponse)(
      result,
    )
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.RespondToListenerYieldPrompt
   */
  async RespondToListenerYieldPrompt(
    request: RespondToListenerYieldPromptRequest,
    abortSignal?: AbortSignal,
  ): Promise<RespondToListenerYieldPromptResponse> {
    const requestMsg = RespondToListenerYieldPromptRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.RespondToListenerYieldPrompt.name,
      RespondToListenerYieldPromptRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return RespondToListenerYieldPromptResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchRuntimeHandoff
   */
  WatchRuntimeHandoff(
    request: WatchRuntimeHandoffRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchRuntimeHandoffResponse> {
    const requestMsg = WatchRuntimeHandoffRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchRuntimeHandoff.name,
      WatchRuntimeHandoffRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchRuntimeHandoffResponse)(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.ReclaimRuntime
   */
  async ReclaimRuntime(
    request: ReclaimRuntimeRequest,
    abortSignal?: AbortSignal,
  ): Promise<ReclaimRuntimeResponse> {
    const requestMsg = ReclaimRuntimeRequest.create(request)
    const result = await this.rpc.request(
      this.service,
      RootResourceServiceDefinition.methods.ReclaimRuntime.name,
      ReclaimRuntimeRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return ReclaimRuntimeResponse.fromBinary(result)
  }

  /**
   * @generated from rpc s4wave.root.RootResourceService.WatchListenerStatus
   */
  WatchListenerStatus(
    request: WatchListenerStatusRequest,
    abortSignal?: AbortSignal,
  ): MessageStream<WatchListenerStatusResponse> {
    const requestMsg = WatchListenerStatusRequest.create(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      RootResourceServiceDefinition.methods.WatchListenerStatus.name,
      WatchListenerStatusRequest.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(WatchListenerStatusResponse)(result)
  }
}
