// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.18.1-0.20260826222423-298dca0e6eaf
// source: github.com/s4wave/spacewave/core/pairing/pairing.proto

package pairing

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	session "github.com/s4wave/spacewave/core/session"
	sobject "github.com/s4wave/spacewave/core/sobject"
)

// AccountOutcome selects the account relationship created by bilateral approval.
type AccountOutcome int32

const (
	// AccountOutcome_UNSPECIFIED requires the receiving client to choose an outcome.
	AccountOutcome_AccountOutcome_UNSPECIFIED AccountOutcome = 0
	// AccountOutcome_SIGN_IN_OFFERED adds the code creator's account on the receiving client.
	AccountOutcome_AccountOutcome_SIGN_IN_OFFERED AccountOutcome = 1
	// AccountOutcome_SIGN_IN_RECEIVING adds the receiving client's account on the code creator.
	AccountOutcome_AccountOutcome_SIGN_IN_RECEIVING AccountOutcome = 2
	// AccountOutcome_MERGE_INTO_OFFERED moves the receiving account into the offered account.
	AccountOutcome_AccountOutcome_MERGE_INTO_OFFERED AccountOutcome = 3
	// AccountOutcome_MERGE_INTO_RECEIVING moves the offered account into the receiving account.
	AccountOutcome_AccountOutcome_MERGE_INTO_RECEIVING AccountOutcome = 4
)

// Enum value maps for AccountOutcome.
var (
	AccountOutcome_name = map[int32]string{
		0: "AccountOutcome_UNSPECIFIED",
		1: "AccountOutcome_SIGN_IN_OFFERED",
		2: "AccountOutcome_SIGN_IN_RECEIVING",
		3: "AccountOutcome_MERGE_INTO_OFFERED",
		4: "AccountOutcome_MERGE_INTO_RECEIVING",
	}
	AccountOutcome_value = map[string]int32{
		"AccountOutcome_UNSPECIFIED":          0,
		"AccountOutcome_SIGN_IN_OFFERED":      1,
		"AccountOutcome_SIGN_IN_RECEIVING":    2,
		"AccountOutcome_MERGE_INTO_OFFERED":   3,
		"AccountOutcome_MERGE_INTO_RECEIVING": 4,
	}
)

func (x AccountOutcome) Enum() *AccountOutcome {
	p := new(AccountOutcome)
	*p = x
	return p
}

func (x AccountOutcome) String() string {
	name, valid := AccountOutcome_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Approval is exchanged over a bifrost link during the
// mutual SAS verification step. Both peers send their confirmation
// status and wait for the remote's response.
type Approval struct {
	unknownFields []byte
	// Confirmed indicates the user verified the SAS emoji match.
	Confirmed bool `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	// Rejected indicates the user rejected the SAS emoji match.
	Rejected bool `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	// OperationContext binds approval to the selected account and both receiving keys.
	OperationContext string `protobuf:"bytes,3,opt,name=operation_context,json=operationContext,proto3" json:"operationContext,omitempty"`
}

func (x *Approval) Reset() {
	*x = Approval{}
}

func (*Approval) ProtoMessage() {}

func (x *Approval) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *Approval) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

func (x *Approval) GetOperationContext() string {
	if x != nil {
		return x.OperationContext
	}
	return ""
}

// AccountOffer identifies the account offered over an authenticated pairing stream.
type AccountOffer struct {
	unknownFields []byte
	// AccountId is the logical ProviderAccount selected for enrollment.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"accountId,omitempty"`
	// SettingsId is the canonical account settings SharedObject.
	SettingsId string `protobuf:"bytes,2,opt,name=settings_id,json=settingsId,proto3" json:"settingsId,omitempty"`
	// OperationId binds enrollment proofs to this pairing attempt.
	OperationId string `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operationId,omitempty"`
	// StoragePeerId is the source account's storage participant identity.
	StoragePeerId string `protobuf:"bytes,4,opt,name=storage_peer_id,json=storagePeerId,proto3" json:"storagePeerId,omitempty"`
	// DisplayName identifies the offered account in the approval screen.
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty"`
	// ProviderId selects a configured provider on the receiving client.
	ProviderId string `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"providerId,omitempty"`
	// ProviderEndpoint binds cloud enrollment to the configured provider service.
	ProviderEndpoint string `protobuf:"bytes,7,opt,name=provider_endpoint,json=providerEndpoint,proto3" json:"providerEndpoint,omitempty"`
	// RevokedSessionPeerIds require a new receiving Session identity when repairing access.
	RevokedSessionPeerIds []string `protobuf:"bytes,8,rep,name=revoked_session_peer_ids,json=revokedSessionPeerIds,proto3" json:"revokedSessionPeerIds,omitempty"`
	// ActiveSessionPeerIds identifies current cloud authorizations for Session reuse.
	ActiveSessionPeerIds []string `protobuf:"bytes,9,rep,name=active_session_peer_ids,json=activeSessionPeerIds,proto3" json:"activeSessionPeerIds,omitempty"`
	// SelectionContext binds this enrollment to both accounts and the selected outcome.
	SelectionContext string `protobuf:"bytes,10,opt,name=selection_context,json=selectionContext,proto3" json:"selectionContext,omitempty"`
	// MachineName identifies the client offering this account.
	MachineName string `protobuf:"bytes,11,opt,name=machine_name,json=machineName,proto3" json:"machineName,omitempty"`
	// SpaceCount and SessionCount describe the current migration preview.
	SpaceCount   uint32 `protobuf:"varint,12,opt,name=space_count,json=spaceCount,proto3" json:"spaceCount,omitempty"`
	SessionCount uint32 `protobuf:"varint,13,opt,name=session_count,json=sessionCount,proto3" json:"sessionCount,omitempty"`
}

func (x *AccountOffer) Reset() {
	*x = AccountOffer{}
}

func (*AccountOffer) ProtoMessage() {}

func (x *AccountOffer) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountOffer) GetSettingsId() string {
	if x != nil {
		return x.SettingsId
	}
	return ""
}

func (x *AccountOffer) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AccountOffer) GetStoragePeerId() string {
	if x != nil {
		return x.StoragePeerId
	}
	return ""
}

func (x *AccountOffer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AccountOffer) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AccountOffer) GetProviderEndpoint() string {
	if x != nil {
		return x.ProviderEndpoint
	}
	return ""
}

func (x *AccountOffer) GetRevokedSessionPeerIds() []string {
	if x != nil {
		return x.RevokedSessionPeerIds
	}
	return nil
}

func (x *AccountOffer) GetActiveSessionPeerIds() []string {
	if x != nil {
		return x.ActiveSessionPeerIds
	}
	return nil
}

func (x *AccountOffer) GetSelectionContext() string {
	if x != nil {
		return x.SelectionContext
	}
	return ""
}

func (x *AccountOffer) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *AccountOffer) GetSpaceCount() uint32 {
	if x != nil {
		return x.SpaceCount
	}
	return 0
}

func (x *AccountOffer) GetSessionCount() uint32 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

// AccountChoice carries the two account identities and the selected relationship.
type AccountChoice struct {
	unknownFields []byte
	// OfferedAccount is the account selected by the code creator.
	OfferedAccount *AccountOffer `protobuf:"bytes,1,opt,name=offered_account,json=offeredAccount,proto3" json:"offeredAccount,omitempty"`
	// ReceivingAccount is absent when pairing from Home without a selected account.
	ReceivingAccount *AccountOffer `protobuf:"bytes,2,opt,name=receiving_account,json=receivingAccount,proto3" json:"receivingAccount,omitempty"`
	// Outcome is fixed before either client approves the operation.
	Outcome AccountOutcome `protobuf:"varint,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *AccountChoice) Reset() {
	*x = AccountChoice{}
}

func (*AccountChoice) ProtoMessage() {}

func (x *AccountChoice) GetOfferedAccount() *AccountOffer {
	if x != nil {
		return x.OfferedAccount
	}
	return nil
}

func (x *AccountChoice) GetReceivingAccount() *AccountOffer {
	if x != nil {
		return x.ReceivingAccount
	}
	return nil
}

func (x *AccountChoice) GetOutcome() AccountOutcome {
	if x != nil {
		return x.Outcome
	}
	return AccountOutcome_AccountOutcome_UNSPECIFIED
}

// Identity proves possession of the receiving Session and storage keys.
type Identity struct {
	unknownFields []byte
	// SessionRef is the independently generated receiving Session.
	SessionRef *session.SessionRef `protobuf:"bytes,1,opt,name=session_ref,json=sessionRef,proto3" json:"sessionRef,omitempty"`
	// SessionProof binds the receiving Session key to the offered operation.
	SessionProof *sobject.SOJoinResponse `protobuf:"bytes,2,opt,name=session_proof,json=sessionProof,proto3" json:"sessionProof,omitempty"`
	// StorageProof binds the replica volume key to the same operation.
	StorageProof *sobject.SOJoinResponse `protobuf:"bytes,3,opt,name=storage_proof,json=storageProof,proto3" json:"storageProof,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
}

func (*Identity) ProtoMessage() {}

func (x *Identity) GetSessionRef() *session.SessionRef {
	if x != nil {
		return x.SessionRef
	}
	return nil
}

func (x *Identity) GetSessionProof() *sobject.SOJoinResponse {
	if x != nil {
		return x.SessionProof
	}
	return nil
}

func (x *Identity) GetStorageProof() *sobject.SOJoinResponse {
	if x != nil {
		return x.StorageProof
	}
	return nil
}

// SharedObject carries one authorized bootstrap checkpoint.
type SharedObject struct {
	unknownFields []byte
	// Entry describes the object's identity and body type.
	Entry *sobject.SharedObjectListEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// State is accepted only through the SharedObject host's enrollment contract.
	State *sobject.SOState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// HistoryBase and History retain the verified lineage leading to State.
	HistoryBase *sobject.SharedObjectConfig `protobuf:"bytes,3,opt,name=history_base,json=historyBase,proto3" json:"historyBase,omitempty"`
	History     []*sobject.SOConfigChange   `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	// Genesis retains the signed first entry when HistoryBase is that entry.
	Genesis *sobject.SOConfigChange `protobuf:"bytes,5,opt,name=genesis,proto3" json:"genesis,omitempty"`
}

func (x *SharedObject) Reset() {
	*x = SharedObject{}
}

func (*SharedObject) ProtoMessage() {}

func (x *SharedObject) GetEntry() *sobject.SharedObjectListEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *SharedObject) GetState() *sobject.SOState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SharedObject) GetHistoryBase() *sobject.SharedObjectConfig {
	if x != nil {
		return x.HistoryBase
	}
	return nil
}

func (x *SharedObject) GetHistory() []*sobject.SOConfigChange {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *SharedObject) GetGenesis() *sobject.SOConfigChange {
	if x != nil {
		return x.Genesis
	}
	return nil
}

// Frame carries the ordered account enrollment exchange.
type Frame struct {
	unknownFields []byte
	// Types that are assignable to Body:
	//	*Frame_Account
	//	*Frame_Identity
	//	*Frame_Object
	//	*Frame_Complete
	//	*Frame_Error
	//	*Frame_Choice
	Body isFrame_Body `protobuf_oneof:"body"`
}

func (x *Frame) Reset() {
	*x = Frame{}
}

func (*Frame) ProtoMessage() {}

func (m *Frame) GetBody() isFrame_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Frame) GetAccount() *AccountOffer {
	if x, ok := x.GetBody().(*Frame_Account); ok {
		return x.Account
	}
	return nil
}

func (x *Frame) GetIdentity() *Identity {
	if x, ok := x.GetBody().(*Frame_Identity); ok {
		return x.Identity
	}
	return nil
}

func (x *Frame) GetObject() *SharedObject {
	if x, ok := x.GetBody().(*Frame_Object); ok {
		return x.Object
	}
	return nil
}

func (x *Frame) GetComplete() bool {
	if x, ok := x.GetBody().(*Frame_Complete); ok {
		return x.Complete
	}
	return false
}

func (x *Frame) GetError() string {
	if x, ok := x.GetBody().(*Frame_Error); ok {
		return x.Error
	}
	return ""
}

func (x *Frame) GetChoice() *AccountChoice {
	if x, ok := x.GetBody().(*Frame_Choice); ok {
		return x.Choice
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Account struct {
	// Account offers an existing account before user approval.
	Account *AccountOffer `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type Frame_Identity struct {
	// Identity supplies the receiving client identities before approval.
	Identity *Identity `protobuf:"bytes,2,opt,name=identity,proto3,oneof"`
}

type Frame_Object struct {
	// Object transfers an authorized object after bilateral approval.
	Object *SharedObject `protobuf:"bytes,3,opt,name=object,proto3,oneof"`
}

type Frame_Complete struct {
	// Complete ends object transfer or acknowledges durable enrollment.
	Complete bool `protobuf:"varint,4,opt,name=complete,proto3,oneof"`
}

type Frame_Error struct {
	// Error terminates enrollment with a reason visible to both clients.
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type Frame_Choice struct {
	// Choice selects the relationship after both account identities are known.
	Choice *AccountChoice `protobuf:"bytes,6,opt,name=choice,proto3,oneof"`
}

func (*Frame_Account) isFrame_Body() {}

func (*Frame_Identity) isFrame_Body() {}

func (*Frame_Object) isFrame_Body() {}

func (*Frame_Complete) isFrame_Body() {}

func (*Frame_Error) isFrame_Body() {}

func (*Frame_Choice) isFrame_Body() {}

func (m *Approval) CloneVT() *Approval {
	if m == nil {
		return (*Approval)(nil)
	}
	r := new(Approval)
	r.Confirmed = m.Confirmed
	r.Rejected = m.Rejected
	r.OperationContext = m.OperationContext
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Approval) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *AccountOffer) CloneVT() *AccountOffer {
	if m == nil {
		return (*AccountOffer)(nil)
	}
	r := new(AccountOffer)
	r.AccountId = m.AccountId
	r.SettingsId = m.SettingsId
	r.OperationId = m.OperationId
	r.StoragePeerId = m.StoragePeerId
	r.DisplayName = m.DisplayName
	r.ProviderId = m.ProviderId
	r.ProviderEndpoint = m.ProviderEndpoint
	r.SelectionContext = m.SelectionContext
	r.MachineName = m.MachineName
	r.SpaceCount = m.SpaceCount
	r.SessionCount = m.SessionCount
	r.RevokedSessionPeerIds = protobuf_go_lite.CloneSlice(m.RevokedSessionPeerIds)
	r.ActiveSessionPeerIds = protobuf_go_lite.CloneSlice(m.ActiveSessionPeerIds)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *AccountOffer) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *AccountChoice) CloneVT() *AccountChoice {
	if m == nil {
		return (*AccountChoice)(nil)
	}
	r := new(AccountChoice)
	r.Outcome = m.Outcome
	r.OfferedAccount = protobuf_go_lite.CloneVTValue(m.OfferedAccount)
	r.ReceivingAccount = protobuf_go_lite.CloneVTValue(m.ReceivingAccount)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *AccountChoice) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Identity) CloneVT() *Identity {
	if m == nil {
		return (*Identity)(nil)
	}
	r := new(Identity)
	r.SessionRef = protobuf_go_lite.CloneVTValue(m.SessionRef)
	r.SessionProof = protobuf_go_lite.CloneVTValue(m.SessionProof)
	r.StorageProof = protobuf_go_lite.CloneVTValue(m.StorageProof)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Identity) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *SharedObject) CloneVT() *SharedObject {
	if m == nil {
		return (*SharedObject)(nil)
	}
	r := new(SharedObject)
	r.Entry = protobuf_go_lite.CloneVTValue(m.Entry)
	r.State = protobuf_go_lite.CloneVTValue(m.State)
	r.HistoryBase = protobuf_go_lite.CloneVTValue(m.HistoryBase)
	r.History = protobuf_go_lite.CloneVTSlice(m.History)
	r.Genesis = protobuf_go_lite.CloneVTValue(m.Genesis)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *SharedObject) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Frame) CloneVT() *Frame {
	if m == nil {
		return (*Frame)(nil)
	}
	r := new(Frame)
	if m.Body != nil {
		r.Body = m.Body.(interface{ CloneOneofVT() isFrame_Body }).CloneOneofVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Frame) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Frame_Account) CloneVT() *Frame_Account {
	if m == nil {
		return (*Frame_Account)(nil)
	}
	r := new(Frame_Account)
	r.Account = protobuf_go_lite.CloneVTValue(m.Account)
	return r
}

func (m *Frame_Account) CloneOneofVT() isFrame_Body {
	return m.CloneVT()
}

func (m *Frame_Identity) CloneVT() *Frame_Identity {
	if m == nil {
		return (*Frame_Identity)(nil)
	}
	r := new(Frame_Identity)
	r.Identity = protobuf_go_lite.CloneVTValue(m.Identity)
	return r
}

func (m *Frame_Identity) CloneOneofVT() isFrame_Body {
	return m.CloneVT()
}

func (m *Frame_Object) CloneVT() *Frame_Object {
	if m == nil {
		return (*Frame_Object)(nil)
	}
	r := new(Frame_Object)
	r.Object = protobuf_go_lite.CloneVTValue(m.Object)
	return r
}

func (m *Frame_Object) CloneOneofVT() isFrame_Body {
	return m.CloneVT()
}

func (m *Frame_Complete) CloneVT() *Frame_Complete {
	if m == nil {
		return (*Frame_Complete)(nil)
	}
	r := new(Frame_Complete)
	r.Complete = m.Complete
	return r
}

func (m *Frame_Complete) CloneOneofVT() isFrame_Body {
	return m.CloneVT()
}

func (m *Frame_Error) CloneVT() *Frame_Error {
	if m == nil {
		return (*Frame_Error)(nil)
	}
	r := new(Frame_Error)
	r.Error = m.Error
	return r
}

func (m *Frame_Error) CloneOneofVT() isFrame_Body {
	return m.CloneVT()
}

func (m *Frame_Choice) CloneVT() *Frame_Choice {
	if m == nil {
		return (*Frame_Choice)(nil)
	}
	r := new(Frame_Choice)
	r.Choice = protobuf_go_lite.CloneVTValue(m.Choice)
	return r
}

func (m *Frame_Choice) CloneOneofVT() isFrame_Body {
	return m.CloneVT()
}

func (this *Approval) EqualVT(that *Approval) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Confirmed != that.Confirmed {
		return false
	}
	if this.Rejected != that.Rejected {
		return false
	}
	if this.OperationContext != that.OperationContext {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Approval) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Approval)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *AccountOffer) EqualVT(that *AccountOffer) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.AccountId != that.AccountId {
		return false
	}
	if this.SettingsId != that.SettingsId {
		return false
	}
	if this.OperationId != that.OperationId {
		return false
	}
	if this.StoragePeerId != that.StoragePeerId {
		return false
	}
	if this.DisplayName != that.DisplayName {
		return false
	}
	if this.ProviderId != that.ProviderId {
		return false
	}
	if this.ProviderEndpoint != that.ProviderEndpoint {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.RevokedSessionPeerIds, that.RevokedSessionPeerIds) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.ActiveSessionPeerIds, that.ActiveSessionPeerIds) {
		return false
	}
	if this.SelectionContext != that.SelectionContext {
		return false
	}
	if this.MachineName != that.MachineName {
		return false
	}
	if this.SpaceCount != that.SpaceCount {
		return false
	}
	if this.SessionCount != that.SessionCount {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *AccountOffer) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*AccountOffer)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *AccountChoice) EqualVT(that *AccountChoice) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.OfferedAccount, that.OfferedAccount) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.ReceivingAccount, that.ReceivingAccount) {
		return false
	}
	if this.Outcome != that.Outcome {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *AccountChoice) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*AccountChoice)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Identity) EqualVT(that *Identity) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.SessionRef, that.SessionRef) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.SessionProof, that.SessionProof) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.StorageProof, that.StorageProof) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Identity) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Identity)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *SharedObject) EqualVT(that *SharedObject) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Entry, that.Entry) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.State, that.State) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.HistoryBase, that.HistoryBase) {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.History, that.History, func() *sobject.SOConfigChange { return &sobject.SOConfigChange{} }) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Genesis, that.Genesis) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SharedObject) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*SharedObject)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Frame) EqualVT(that *Frame) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Body == nil && that.Body != nil {
		return false
	} else if this.Body != nil {
		if that.Body == nil {
			return false
		}
		if !this.Body.(interface{ EqualVT(isFrame_Body) bool }).EqualVT(that.Body) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Frame) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Frame)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Frame_Account) EqualVT(thatIface isFrame_Body) bool {
	that, ok := thatIface.(*Frame_Account)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Account, that.Account, func() *AccountOffer { return &AccountOffer{} }) {
		return false
	}
	return true
}

func (this *Frame_Identity) EqualVT(thatIface isFrame_Body) bool {
	that, ok := thatIface.(*Frame_Identity)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Identity, that.Identity, func() *Identity { return &Identity{} }) {
		return false
	}
	return true
}

func (this *Frame_Object) EqualVT(thatIface isFrame_Body) bool {
	that, ok := thatIface.(*Frame_Object)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Object, that.Object, func() *SharedObject { return &SharedObject{} }) {
		return false
	}
	return true
}

func (this *Frame_Complete) EqualVT(thatIface isFrame_Body) bool {
	that, ok := thatIface.(*Frame_Complete)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Complete != that.Complete {
		return false
	}
	return true
}

func (this *Frame_Error) EqualVT(thatIface isFrame_Body) bool {
	that, ok := thatIface.(*Frame_Error)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Error != that.Error {
		return false
	}
	return true
}

func (this *Frame_Choice) EqualVT(thatIface isFrame_Body) bool {
	that, ok := thatIface.(*Frame_Choice)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Choice, that.Choice, func() *AccountChoice { return &AccountChoice{} }) {
		return false
	}
	return true
}

// MarshalProtoJSON marshals the AccountOutcome to JSON.
func (x AccountOutcome) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), AccountOutcome_name)
}

// MarshalText marshals the AccountOutcome to text.
func (x AccountOutcome) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), AccountOutcome_name)), nil
}

// MarshalJSON marshals the AccountOutcome to JSON.
func (x AccountOutcome) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the AccountOutcome from JSON.
func (x *AccountOutcome) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(AccountOutcome_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read AccountOutcome enum: %v", err)
		return
	}
	*x = AccountOutcome(v)
}

// UnmarshalText unmarshals the AccountOutcome from text.
func (x *AccountOutcome) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), AccountOutcome_value)
	if err != nil {
		return err
	}
	*x = AccountOutcome(i)
	return nil
}

// UnmarshalJSON unmarshals the AccountOutcome from JSON.
func (x *AccountOutcome) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Approval message to JSON.
func (x *Approval) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Confirmed || s.HasField("confirmed") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("confirmed")
		s.WriteBool(x.Confirmed)
	}
	if x.Rejected || s.HasField("rejected") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rejected")
		s.WriteBool(x.Rejected)
	}
	if x.OperationContext != "" || s.HasField("operationContext") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("operationContext")
		s.WriteString(x.OperationContext)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Approval to JSON.
func (x *Approval) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Approval message from JSON.
func (x *Approval) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "confirmed":
			s.AddField("confirmed")
			x.Confirmed = s.ReadBool()
		case "rejected":
			s.AddField("rejected")
			x.Rejected = s.ReadBool()
		case "operation_context", "operationContext":
			s.AddField("operation_context")
			x.OperationContext = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Approval from JSON.
func (x *Approval) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the AccountOffer message to JSON.
func (x *AccountOffer) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.AccountId != "" || s.HasField("accountId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("accountId")
		s.WriteString(x.AccountId)
	}
	if x.SettingsId != "" || s.HasField("settingsId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("settingsId")
		s.WriteString(x.SettingsId)
	}
	if x.OperationId != "" || s.HasField("operationId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("operationId")
		s.WriteString(x.OperationId)
	}
	if x.StoragePeerId != "" || s.HasField("storagePeerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("storagePeerId")
		s.WriteString(x.StoragePeerId)
	}
	if x.DisplayName != "" || s.HasField("displayName") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("displayName")
		s.WriteString(x.DisplayName)
	}
	if x.ProviderId != "" || s.HasField("providerId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("providerId")
		s.WriteString(x.ProviderId)
	}
	if x.ProviderEndpoint != "" || s.HasField("providerEndpoint") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("providerEndpoint")
		s.WriteString(x.ProviderEndpoint)
	}
	if len(x.RevokedSessionPeerIds) > 0 || s.HasField("revokedSessionPeerIds") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("revokedSessionPeerIds")
		s.WriteStringArray(x.RevokedSessionPeerIds)
	}
	if len(x.ActiveSessionPeerIds) > 0 || s.HasField("activeSessionPeerIds") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("activeSessionPeerIds")
		s.WriteStringArray(x.ActiveSessionPeerIds)
	}
	if x.SelectionContext != "" || s.HasField("selectionContext") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("selectionContext")
		s.WriteString(x.SelectionContext)
	}
	if x.MachineName != "" || s.HasField("machineName") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("machineName")
		s.WriteString(x.MachineName)
	}
	if x.SpaceCount != 0 || s.HasField("spaceCount") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("spaceCount")
		s.WriteUint32(x.SpaceCount)
	}
	if x.SessionCount != 0 || s.HasField("sessionCount") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sessionCount")
		s.WriteUint32(x.SessionCount)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the AccountOffer to JSON.
func (x *AccountOffer) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the AccountOffer message from JSON.
func (x *AccountOffer) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "account_id", "accountId":
			s.AddField("account_id")
			x.AccountId = s.ReadString()
		case "settings_id", "settingsId":
			s.AddField("settings_id")
			x.SettingsId = s.ReadString()
		case "operation_id", "operationId":
			s.AddField("operation_id")
			x.OperationId = s.ReadString()
		case "storage_peer_id", "storagePeerId":
			s.AddField("storage_peer_id")
			x.StoragePeerId = s.ReadString()
		case "display_name", "displayName":
			s.AddField("display_name")
			x.DisplayName = s.ReadString()
		case "provider_id", "providerId":
			s.AddField("provider_id")
			x.ProviderId = s.ReadString()
		case "provider_endpoint", "providerEndpoint":
			s.AddField("provider_endpoint")
			x.ProviderEndpoint = s.ReadString()
		case "revoked_session_peer_ids", "revokedSessionPeerIds":
			s.AddField("revoked_session_peer_ids")
			if s.ReadNil() {
				x.RevokedSessionPeerIds = nil
				return
			}
			x.RevokedSessionPeerIds = s.ReadStringArray()
		case "active_session_peer_ids", "activeSessionPeerIds":
			s.AddField("active_session_peer_ids")
			if s.ReadNil() {
				x.ActiveSessionPeerIds = nil
				return
			}
			x.ActiveSessionPeerIds = s.ReadStringArray()
		case "selection_context", "selectionContext":
			s.AddField("selection_context")
			x.SelectionContext = s.ReadString()
		case "machine_name", "machineName":
			s.AddField("machine_name")
			x.MachineName = s.ReadString()
		case "space_count", "spaceCount":
			s.AddField("space_count")
			x.SpaceCount = s.ReadUint32()
		case "session_count", "sessionCount":
			s.AddField("session_count")
			x.SessionCount = s.ReadUint32()
		}
	})
}

// UnmarshalJSON unmarshals the AccountOffer from JSON.
func (x *AccountOffer) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the AccountChoice message to JSON.
func (x *AccountChoice) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.OfferedAccount != nil || s.HasField("offeredAccount") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("offeredAccount")
		x.OfferedAccount.MarshalProtoJSON(s.WithField("offeredAccount"))
	}
	if x.ReceivingAccount != nil || s.HasField("receivingAccount") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("receivingAccount")
		x.ReceivingAccount.MarshalProtoJSON(s.WithField("receivingAccount"))
	}
	if x.Outcome != 0 || s.HasField("outcome") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("outcome")
		x.Outcome.MarshalProtoJSON(s)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the AccountChoice to JSON.
func (x *AccountChoice) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the AccountChoice message from JSON.
func (x *AccountChoice) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "offered_account", "offeredAccount":
			if s.ReadNil() {
				x.OfferedAccount = nil
				return
			}
			x.OfferedAccount = &AccountOffer{}
			x.OfferedAccount.UnmarshalProtoJSON(s.WithField("offered_account", true))
		case "receiving_account", "receivingAccount":
			if s.ReadNil() {
				x.ReceivingAccount = nil
				return
			}
			x.ReceivingAccount = &AccountOffer{}
			x.ReceivingAccount.UnmarshalProtoJSON(s.WithField("receiving_account", true))
		case "outcome":
			s.AddField("outcome")
			x.Outcome.UnmarshalProtoJSON(s)
		}
	})
}

// UnmarshalJSON unmarshals the AccountChoice from JSON.
func (x *AccountChoice) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Identity message to JSON.
func (x *Identity) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.SessionRef != nil || s.HasField("sessionRef") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sessionRef")
		x.SessionRef.MarshalProtoJSON(s.WithField("sessionRef"))
	}
	if x.SessionProof != nil || s.HasField("sessionProof") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sessionProof")
		x.SessionProof.MarshalProtoJSON(s.WithField("sessionProof"))
	}
	if x.StorageProof != nil || s.HasField("storageProof") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("storageProof")
		x.StorageProof.MarshalProtoJSON(s.WithField("storageProof"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Identity to JSON.
func (x *Identity) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Identity message from JSON.
func (x *Identity) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "session_ref", "sessionRef":
			if s.ReadNil() {
				x.SessionRef = nil
				return
			}
			x.SessionRef = &session.SessionRef{}
			x.SessionRef.UnmarshalProtoJSON(s.WithField("session_ref", true))
		case "session_proof", "sessionProof":
			if s.ReadNil() {
				x.SessionProof = nil
				return
			}
			x.SessionProof = &sobject.SOJoinResponse{}
			x.SessionProof.UnmarshalProtoJSON(s.WithField("session_proof", true))
		case "storage_proof", "storageProof":
			if s.ReadNil() {
				x.StorageProof = nil
				return
			}
			x.StorageProof = &sobject.SOJoinResponse{}
			x.StorageProof.UnmarshalProtoJSON(s.WithField("storage_proof", true))
		}
	})
}

// UnmarshalJSON unmarshals the Identity from JSON.
func (x *Identity) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the SharedObject message to JSON.
func (x *SharedObject) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Entry != nil || s.HasField("entry") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("entry")
		x.Entry.MarshalProtoJSON(s.WithField("entry"))
	}
	if x.State != nil || s.HasField("state") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("state")
		x.State.MarshalProtoJSON(s.WithField("state"))
	}
	if x.HistoryBase != nil || s.HasField("historyBase") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("historyBase")
		x.HistoryBase.MarshalProtoJSON(s.WithField("historyBase"))
	}
	if len(x.History) > 0 || s.HasField("history") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("history")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.History {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("history"))
		}
		s.WriteArrayEnd()
	}
	if x.Genesis != nil || s.HasField("genesis") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("genesis")
		x.Genesis.MarshalProtoJSON(s.WithField("genesis"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the SharedObject to JSON.
func (x *SharedObject) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the SharedObject message from JSON.
func (x *SharedObject) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "entry":
			if s.ReadNil() {
				x.Entry = nil
				return
			}
			x.Entry = &sobject.SharedObjectListEntry{}
			x.Entry.UnmarshalProtoJSON(s.WithField("entry", true))
		case "state":
			if s.ReadNil() {
				x.State = nil
				return
			}
			x.State = &sobject.SOState{}
			x.State.UnmarshalProtoJSON(s.WithField("state", true))
		case "history_base", "historyBase":
			if s.ReadNil() {
				x.HistoryBase = nil
				return
			}
			x.HistoryBase = &sobject.SharedObjectConfig{}
			x.HistoryBase.UnmarshalProtoJSON(s.WithField("history_base", true))
		case "history":
			s.AddField("history")
			if s.ReadNil() {
				x.History = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.History = append(x.History, nil)
					return
				}
				v := &sobject.SOConfigChange{}
				v.UnmarshalProtoJSON(s.WithField("history", false))
				if s.Err() != nil {
					return
				}
				x.History = append(x.History, v)
			})
		case "genesis":
			if s.ReadNil() {
				x.Genesis = nil
				return
			}
			x.Genesis = &sobject.SOConfigChange{}
			x.Genesis.UnmarshalProtoJSON(s.WithField("genesis", true))
		}
	})
}

// UnmarshalJSON unmarshals the SharedObject from JSON.
func (x *SharedObject) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Frame message to JSON.
func (x *Frame) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Body != nil {
		switch ov := x.Body.(type) {
		case *Frame_Account:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("account")
			ov.Account.MarshalProtoJSON(s.WithField("account"))
		case *Frame_Identity:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("identity")
			ov.Identity.MarshalProtoJSON(s.WithField("identity"))
		case *Frame_Object:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("object")
			ov.Object.MarshalProtoJSON(s.WithField("object"))
		case *Frame_Complete:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("complete")
			s.WriteBool(ov.Complete)
		case *Frame_Error:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("error")
			s.WriteString(ov.Error)
		case *Frame_Choice:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("choice")
			ov.Choice.MarshalProtoJSON(s.WithField("choice"))
		}
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Frame to JSON.
func (x *Frame) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Frame message from JSON.
func (x *Frame) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "account":
			ov := &Frame_Account{}
			x.Body = ov
			if s.ReadNil() {
				ov.Account = nil
				return
			}
			ov.Account = &AccountOffer{}
			ov.Account.UnmarshalProtoJSON(s.WithField("account", true))
		case "identity":
			ov := &Frame_Identity{}
			x.Body = ov
			if s.ReadNil() {
				ov.Identity = nil
				return
			}
			ov.Identity = &Identity{}
			ov.Identity.UnmarshalProtoJSON(s.WithField("identity", true))
		case "object":
			ov := &Frame_Object{}
			x.Body = ov
			if s.ReadNil() {
				ov.Object = nil
				return
			}
			ov.Object = &SharedObject{}
			ov.Object.UnmarshalProtoJSON(s.WithField("object", true))
		case "complete":
			s.AddField("complete")
			ov := &Frame_Complete{}
			x.Body = ov
			ov.Complete = s.ReadBool()
		case "error":
			s.AddField("error")
			ov := &Frame_Error{}
			x.Body = ov
			ov.Error = s.ReadString()
		case "choice":
			ov := &Frame_Choice{}
			x.Body = ov
			if s.ReadNil() {
				ov.Choice = nil
				return
			}
			ov.Choice = &AccountChoice{}
			ov.Choice.UnmarshalProtoJSON(s.WithField("choice", true))
		}
	})
}

// UnmarshalJSON unmarshals the Frame from JSON.
func (x *Frame) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Approval) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Approval) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Approval) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.OperationContext) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.OperationContext)
		i--
		dAtA[i] = 0x1a
	}
	if m.Rejected {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Rejected)
		i--
		dAtA[i] = 0x10
	}
	if m.Confirmed {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Confirmed)
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AccountOffer) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountOffer) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *AccountOffer) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.SessionCount != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.SessionCount))
		i--
		dAtA[i] = 0x68
	}
	if m.SpaceCount != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.SpaceCount))
		i--
		dAtA[i] = 0x60
	}
	if len(m.MachineName) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.MachineName)
		i--
		dAtA[i] = 0x5a
	}
	if len(m.SelectionContext) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.SelectionContext)
		i--
		dAtA[i] = 0x52
	}
	if len(m.ActiveSessionPeerIds) > 0 {
		for iNdEx := len(m.ActiveSessionPeerIds) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.ActiveSessionPeerIds[iNdEx])
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.RevokedSessionPeerIds) > 0 {
		for iNdEx := len(m.RevokedSessionPeerIds) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.RevokedSessionPeerIds[iNdEx])
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.ProviderEndpoint) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ProviderEndpoint)
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ProviderId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ProviderId)
		i--
		dAtA[i] = 0x32
	}
	if len(m.DisplayName) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.DisplayName)
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StoragePeerId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.StoragePeerId)
		i--
		dAtA[i] = 0x22
	}
	if len(m.OperationId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.OperationId)
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SettingsId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.SettingsId)
		i--
		dAtA[i] = 0x12
	}
	if len(m.AccountId) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.AccountId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountChoice) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountChoice) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *AccountChoice) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Outcome != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Outcome))
		i--
		dAtA[i] = 0x18
	}
	if m.ReceivingAccount != nil {
		size, err := m.ReceivingAccount.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.OfferedAccount != nil {
		size, err := m.OfferedAccount.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Identity) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Identity) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Identity) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.StorageProof != nil {
		size, err := m.StorageProof.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.SessionProof != nil {
		size, err := m.SessionProof.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.SessionRef != nil {
		size, err := m.SessionRef.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SharedObject) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SharedObject) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *SharedObject) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Genesis != nil {
		size, err := m.Genesis.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.History) > 0 {
		for iNdEx := len(m.History) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.History[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.HistoryBase != nil {
		size, err := m.HistoryBase.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.State != nil {
		size, err := m.State.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Entry != nil {
		size, err := m.Entry.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Frame) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Frame) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if vtmsg, ok := m.Body.(interface {
		MarshalToSizedBufferVT([]byte) (int, error)
	}); ok {
		size, err := vtmsg.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
	}
	return len(dAtA) - i, nil
}

func (m *Frame_Account) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame_Account) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Account != nil {
		size, err := m.Account.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Frame_Identity) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame_Identity) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Identity != nil {
		size, err := m.Identity.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *Frame_Object) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame_Object) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Object != nil {
		size, err := m.Object.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}

func (m *Frame_Complete) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame_Complete) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeBool(dAtA, i, m.Complete)
	i--
	dAtA[i] = 0x20
	return len(dAtA) - i, nil
}

func (m *Frame_Error) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame_Error) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeString(dAtA, i, m.Error)
	i--
	dAtA[i] = 0x2a
	return len(dAtA) - i, nil
}

func (m *Frame_Choice) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Frame_Choice) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Choice != nil {
		size, err := m.Choice.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}

func (m *Approval) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Confirmed)
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Rejected)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.OperationContext)
	n += len(m.unknownFields)
	return n
}

func (m *AccountOffer) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.AccountId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.SettingsId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.OperationId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.StoragePeerId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.DisplayName)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ProviderId)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ProviderEndpoint)
	n += protobuf_go_lite.SizeStringSlice(1, m.RevokedSessionPeerIds)
	n += protobuf_go_lite.SizeStringSlice(1, m.ActiveSessionPeerIds)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.SelectionContext)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.MachineName)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.SpaceCount)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.SessionCount)
	n += len(m.unknownFields)
	return n
}

func (m *AccountChoice) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OfferedAccount != nil {
		l = m.OfferedAccount.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.ReceivingAccount != nil {
		l = m.ReceivingAccount.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Outcome)
	n += len(m.unknownFields)
	return n
}

func (m *Identity) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SessionRef != nil {
		l = m.SessionRef.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.SessionProof != nil {
		l = m.SessionProof.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.StorageProof != nil {
		l = m.StorageProof.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *SharedObject) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Entry != nil {
		l = m.Entry.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.State != nil {
		l = m.State.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.HistoryBase != nil {
		l = m.HistoryBase.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	for _, e := range m.History {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Genesis != nil {
		l = m.Genesis.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *Frame) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if vtmsg, ok := m.Body.(interface{ SizeVT() int }); ok {
		n += vtmsg.SizeVT()
	}
	n += len(m.unknownFields)
	return n
}

func (m *Frame_Account) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Account != nil {
		l = m.Account.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Frame_Identity) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Identity != nil {
		l = m.Identity.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Frame_Object) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Object != nil {
		l = m.Object.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Frame_Complete) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolValue(1)
	return n
}

func (m *Frame_Error) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringValue(1, m.Error)
	return n
}

func (m *Frame_Choice) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Choice != nil {
		l = m.Choice.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (x AccountOutcome) MarshalProtoText() string {
	return x.String()
}

func (x *Approval) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Approval")
	if x.Confirmed != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "confirmed")
		protobuf_go_lite.TextWriteBool(&sb, x.Confirmed)
	}
	if x.Rejected != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "rejected")
		protobuf_go_lite.TextWriteBool(&sb, x.Rejected)
	}
	if x.OperationContext != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "operation_context")
		protobuf_go_lite.TextWriteString(&sb, x.OperationContext)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Approval) String() string {
	return x.MarshalProtoText()
}

func (x *AccountOffer) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "AccountOffer")
	if x.AccountId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "account_id")
		protobuf_go_lite.TextWriteString(&sb, x.AccountId)
	}
	if x.SettingsId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "settings_id")
		protobuf_go_lite.TextWriteString(&sb, x.SettingsId)
	}
	if x.OperationId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "operation_id")
		protobuf_go_lite.TextWriteString(&sb, x.OperationId)
	}
	if x.StoragePeerId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "storage_peer_id")
		protobuf_go_lite.TextWriteString(&sb, x.StoragePeerId)
	}
	if x.DisplayName != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "display_name")
		protobuf_go_lite.TextWriteString(&sb, x.DisplayName)
	}
	if x.ProviderId != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "provider_id")
		protobuf_go_lite.TextWriteString(&sb, x.ProviderId)
	}
	if x.ProviderEndpoint != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "provider_endpoint")
		protobuf_go_lite.TextWriteString(&sb, x.ProviderEndpoint)
	}
	if len(x.RevokedSessionPeerIds) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "revoked_session_peer_ids")
		for i, v := range x.RevokedSessionPeerIds {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.ActiveSessionPeerIds) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "active_session_peer_ids")
		for i, v := range x.ActiveSessionPeerIds {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.SelectionContext != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "selection_context")
		protobuf_go_lite.TextWriteString(&sb, x.SelectionContext)
	}
	if x.MachineName != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "machine_name")
		protobuf_go_lite.TextWriteString(&sb, x.MachineName)
	}
	if x.SpaceCount != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "space_count")
		protobuf_go_lite.TextWriteUint(&sb, x.SpaceCount)
	}
	if x.SessionCount != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "session_count")
		protobuf_go_lite.TextWriteUint(&sb, x.SessionCount)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *AccountOffer) String() string {
	return x.MarshalProtoText()
}

func (x *AccountChoice) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "AccountChoice")
	if x.OfferedAccount != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "offered_account")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.OfferedAccount)
	}
	if x.ReceivingAccount != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "receiving_account")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.ReceivingAccount)
	}
	if x.Outcome != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "outcome")
		protobuf_go_lite.TextWriteStringer(&sb, AccountOutcome(x.Outcome))
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *AccountChoice) String() string {
	return x.MarshalProtoText()
}

func (x *Identity) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Identity")
	if x.SessionRef != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "session_ref")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.SessionRef)
	}
	if x.SessionProof != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "session_proof")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.SessionProof)
	}
	if x.StorageProof != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "storage_proof")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.StorageProof)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Identity) String() string {
	return x.MarshalProtoText()
}

func (x *SharedObject) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "SharedObject")
	if x.Entry != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "entry")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Entry)
	}
	if x.State != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "state")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.State)
	}
	if x.HistoryBase != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "history_base")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.HistoryBase)
	}
	if len(x.History) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "history")
		for i, v := range x.History {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &sobject.SOConfigChange{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.Genesis != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "genesis")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Genesis)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *SharedObject) String() string {
	return x.MarshalProtoText()
}

func (x *Frame) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Frame")
	switch body := x.Body.(type) {
	case *Frame_Account:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "account")
		if body.Account == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &AccountOffer{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Account)
		}
	case *Frame_Identity:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "identity")
		if body.Identity == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &Identity{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Identity)
		}
	case *Frame_Object:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "object")
		if body.Object == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &SharedObject{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Object)
		}
	case *Frame_Complete:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "complete")
		protobuf_go_lite.TextWriteBool(&sb, body.Complete)
	case *Frame_Error:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error")
		protobuf_go_lite.TextWriteString(&sb, body.Error)
	case *Frame_Choice:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "choice")
		if body.Choice == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &AccountChoice{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Choice)
		}
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Frame) String() string {
	return x.MarshalProtoText()
}

func (m *Approval) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Approval: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Approval: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confirmed", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Confirmed = bool(v)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rejected", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Rejected = bool(v)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationContext", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.OperationContext = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *AccountOffer) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountOffer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountOffer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AccountId = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettingsId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SettingsId = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.OperationId = v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoragePeerId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.StoragePeerId = v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DisplayName = v
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ProviderId = v
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderEndpoint", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ProviderEndpoint = v
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedSessionPeerIds", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RevokedSessionPeerIds = append(m.RevokedSessionPeerIds, v)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveSessionPeerIds", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ActiveSessionPeerIds = append(m.ActiveSessionPeerIds, v)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectionContext", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SelectionContext = v
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MachineName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.MachineName = v
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpaceCount", wireType)
			}
			m.SpaceCount = 0
			m.SpaceCount, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionCount", wireType)
			}
			m.SessionCount = 0
			m.SessionCount, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *AccountChoice) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountChoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountChoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferedAccount", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.OfferedAccount == nil {
				m.OfferedAccount = &AccountOffer{}
			}
			if err := m.OfferedAccount.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivingAccount", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.ReceivingAccount == nil {
				m.ReceivingAccount = &AccountOffer{}
			}
			if err := m.ReceivingAccount.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outcome", wireType)
			}
			m.Outcome = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.Outcome = AccountOutcome(_v)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Identity) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Identity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Identity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionRef", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.SessionRef == nil {
				m.SessionRef = &session.SessionRef{}
			}
			if err := m.SessionRef.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionProof", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.SessionProof == nil {
				m.SessionProof = &sobject.SOJoinResponse{}
			}
			if err := m.SessionProof.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageProof", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.StorageProof == nil {
				m.StorageProof = &sobject.SOJoinResponse{}
			}
			if err := m.StorageProof.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SharedObject) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SharedObject: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SharedObject: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entry", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Entry == nil {
				m.Entry = &sobject.SharedObjectListEntry{}
			}
			if err := m.Entry.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.State == nil {
				m.State = &sobject.SOState{}
			}
			if err := m.State.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoryBase", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.HistoryBase == nil {
				m.HistoryBase = &sobject.SharedObjectConfig{}
			}
			if err := m.HistoryBase.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.History = append(m.History, &sobject.SOConfigChange{})
			if err := m.History[len(m.History)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Genesis", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Genesis == nil {
				m.Genesis = &sobject.SOConfigChange{}
			}
			if err := m.Genesis.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Frame) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Frame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Frame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Frame_Account); ok {
				if err := oneof.Account.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &AccountOffer{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Frame_Account{Account: v}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identity", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Frame_Identity); ok {
				if err := oneof.Identity.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &Identity{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Frame_Identity{Identity: v}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Object", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Frame_Object); ok {
				if err := oneof.Object.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &SharedObject{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Frame_Object{Object: v}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Complete", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.Body = &Frame_Complete{Complete: b}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Body = &Frame_Error{Error: v}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Choice", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Frame_Choice); ok {
				if err := oneof.Choice.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &AccountChoice{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Frame_Choice{Choice: v}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
