// Code generated by protoc-gen-srpc. DO NOT EDIT.
// protoc-gen-srpc version: v0.52.1
// source: github.com/s4wave/spacewave/sdk/process/process.proto

package s4wave_process

import (
	context "context"

	srpc "github.com/aperturerobotics/starpc/srpc"
)

type SRPCPersistentExecutionServiceClient interface {
	// SRPCClient returns the underlying SRPC client.
	SRPCClient() srpc.Client

	Execute(ctx context.Context, in *ExecuteRequest) (SRPCPersistentExecutionService_ExecuteClient, error)
}

type srpcPersistentExecutionServiceClient struct {
	cc        srpc.Client
	serviceID string
}

func NewSRPCPersistentExecutionServiceClient(cc srpc.Client) SRPCPersistentExecutionServiceClient {
	return &srpcPersistentExecutionServiceClient{cc: cc, serviceID: SRPCPersistentExecutionServiceServiceID}
}

func NewSRPCPersistentExecutionServiceClientWithServiceID(cc srpc.Client, serviceID string) SRPCPersistentExecutionServiceClient {
	if serviceID == "" {
		serviceID = SRPCPersistentExecutionServiceServiceID
	}
	return &srpcPersistentExecutionServiceClient{cc: cc, serviceID: serviceID}
}

func (c *srpcPersistentExecutionServiceClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcPersistentExecutionServiceClient) Execute(ctx context.Context, in *ExecuteRequest) (SRPCPersistentExecutionService_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, c.serviceID, "Execute", in)
	if err != nil {
		return nil, err
	}
	strm := &srpcPersistentExecutionService_ExecuteClient{stream}
	if err := strm.CloseSend(); err != nil {
		return nil, err
	}
	return strm, nil
}

type SRPCPersistentExecutionService_ExecuteClient interface {
	srpc.Stream
	Recv() (*ExecuteStatus, error)
	RecvTo(*ExecuteStatus) error
}

type srpcPersistentExecutionService_ExecuteClient struct {
	srpc.Stream
}

func (x *srpcPersistentExecutionService_ExecuteClient) Recv() (*ExecuteStatus, error) {
	m := new(ExecuteStatus)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *srpcPersistentExecutionService_ExecuteClient) RecvTo(m *ExecuteStatus) error {
	return x.MsgRecv(m)
}

type SRPCPersistentExecutionServiceServer interface {
	Execute(*ExecuteRequest, SRPCPersistentExecutionService_ExecuteStream) error
}

const SRPCPersistentExecutionServiceServiceID = "s4wave.process.PersistentExecutionService"

type SRPCPersistentExecutionServiceHandler struct {
	serviceID string
	impl      SRPCPersistentExecutionServiceServer
}

// NewSRPCPersistentExecutionServiceHandler constructs a new RPC handler.
// serviceID: if empty, uses default: s4wave.process.PersistentExecutionService
func NewSRPCPersistentExecutionServiceHandler(impl SRPCPersistentExecutionServiceServer, serviceID string) srpc.Handler {
	if serviceID == "" {
		serviceID = SRPCPersistentExecutionServiceServiceID
	}
	return &SRPCPersistentExecutionServiceHandler{impl: impl, serviceID: serviceID}
}

// SRPCRegisterPersistentExecutionService registers the implementation with the mux.
// Uses the default serviceID: s4wave.process.PersistentExecutionService
func SRPCRegisterPersistentExecutionService(mux srpc.Mux, impl SRPCPersistentExecutionServiceServer) error {
	return mux.Register(NewSRPCPersistentExecutionServiceHandler(impl, ""))
}

func (d *SRPCPersistentExecutionServiceHandler) GetServiceID() string { return d.serviceID }

func (SRPCPersistentExecutionServiceHandler) GetMethodIDs() []string {
	return []string{
		"Execute",
	}
}

func (d *SRPCPersistentExecutionServiceHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "Execute":
		return true, d.InvokeMethod_Execute(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCPersistentExecutionServiceHandler) InvokeMethod_Execute(impl SRPCPersistentExecutionServiceServer, strm srpc.Stream) error {
	req := new(ExecuteRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	serverStrm := &srpcPersistentExecutionService_ExecuteStream{strm}
	return impl.Execute(req, serverStrm)
}

type SRPCPersistentExecutionService_ExecuteStream interface {
	srpc.Stream
	Send(*ExecuteStatus) error
	SendAndClose(*ExecuteStatus) error
}

type srpcPersistentExecutionService_ExecuteStream struct {
	srpc.Stream
}

func (x *srpcPersistentExecutionService_ExecuteStream) Send(m *ExecuteStatus) error {
	return x.MsgSend(m)
}

func (x *srpcPersistentExecutionService_ExecuteStream) SendAndClose(m *ExecuteStatus) error {
	if m != nil {
		if err := x.MsgSend(m); err != nil {
			return err
		}
	}
	return x.CloseSend()
}
