// @generated
// This file is @generated by prost-build.
/// Config configures a http server that listens on a port.
///
/// Handles incoming requests with LookupHTTPHandler.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// Addr is the address to listen.
    ///
    /// Example: 0.0.0.0:8080
    #[prost(string, tag="1")]
    pub addr: ::prost::alloc::string::String,
    /// ClientId is the client id to set on LookupHTTPHandler.
    #[prost(string, tag="2")]
    pub client_id: ::prost::alloc::string::String,
    /// CertFile is the path to the certificate file to use for https.
    /// Can be unset to use HTTP.
    #[prost(string, tag="3")]
    pub cert_file: ::prost::alloc::string::String,
    /// KeyFile is the path to the key file to use for https.
    /// Cannot be unset if cert_file is set.
    /// Otherwise can be unset.
    #[prost(string, tag="4")]
    pub key_file: ::prost::alloc::string::String,
    /// Wait indicates to wait for LookupHTTPHandler even if it becomes idle.
    /// If false: returns 404 not found if LookupHTTPHandler becomes idle.
    #[prost(bool, tag="5")]
    pub wait: bool,
}
// @@protoc_insertion_point(module)
