// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/bifrost/entitygraph/config.proto

package bifrost_entitygraph

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Config is entity graph controller config.
type Config struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_4d1f67466c57fd69, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Config)(nil), "bifrost.entitygraph.Config")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/bifrost/entitygraph/config.proto", fileDescriptor_config_4d1f67466c57fd69)
}

var fileDescriptor_config_4d1f67466c57fd69 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xca, 0x3b, 0x0e, 0x80, 0x20,
	0x0c, 0x00, 0xd0, 0x8d, 0x18, 0x46, 0xbd, 0x81, 0x07, 0xa0, 0x83, 0xab, 0x9b, 0x27, 0xa1, 0x84,
	0x4f, 0x07, 0x29, 0x29, 0x65, 0xf0, 0xf6, 0x26, 0xc4, 0xc1, 0xfd, 0xd9, 0x33, 0x93, 0x96, 0x81,
	0x2e, 0xf0, 0x0d, 0xbe, 0x45, 0xd1, 0x21, 0x51, 0x18, 0x59, 0x29, 0x74, 0x40, 0x4a, 0xc2, 0x5d,
	0x21, 0x56, 0x25, 0x7d, 0xb2, 0xf8, 0x56, 0x20, 0x70, 0x4d, 0x94, 0x5d, 0x13, 0x56, 0x5e, 0xb7,
	0x4f, 0xb8, 0x9f, 0xd8, 0x17, 0x6b, 0xae, 0x89, 0xd0, 0x4c, 0x75, 0xbc, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x6c, 0x4f, 0x4f, 0x48, 0x65, 0x00, 0x00, 0x00,
}
