// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/bifrost/crypto/crypto.proto (package crypto, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import {
  createEnumType,
  createMessageType,
  ScalarType,
} from '@aptre/protobuf-es-lite'

export const protobufPackage = 'crypto'

/**
 * KeyType defines the list of supported crypto key types.
 * This is intended to be drop-in compatible with go-libp2p KeyType.
 *
 * @generated from enum crypto.KeyType
 */
export enum KeyType {
  /**
   * @generated from enum value: RSA = 0;
   */
  RSA = 0,

  /**
   * @generated from enum value: Ed25519 = 1;
   */
  Ed25519 = 1,
}

// KeyType_Enum is the enum type for KeyType.
export const KeyType_Enum = createEnumType('crypto.KeyType', [
  { no: 0, name: 'RSA' },
  { no: 1, name: 'Ed25519' },
])

/**
 * PrivateKey is the protobuf message for private keys.
 *
 * This is wire-compatible with the libp2p PrivateKey type.
 *
 * @generated from message crypto.PrivateKey
 */
export interface PrivateKey {
  /**
   * KeyType is the type of the key.
   *
   * @generated from field: crypto.KeyType key_type = 1;
   */
  keyType?: KeyType
  /**
   * Data is the data of the key.
   *
   * @generated from field: bytes data = 2;
   */
  data?: Uint8Array
}

// PrivateKey contains the message type declaration for PrivateKey.
export const PrivateKey: MessageType<PrivateKey> = createMessageType({
  typeName: 'crypto.PrivateKey',
  fields: [
    { no: 1, name: 'key_type', kind: 'enum', T: KeyType_Enum },
    { no: 2, name: 'data', kind: 'scalar', T: ScalarType.BYTES },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})

/**
 * PublicKey is the protobuf message for public keys.
 *
 * This is wire-compatible with the libp2p PublicKey type.
 *
 * @generated from message crypto.PublicKey
 */
export interface PublicKey {
  /**
   * KeyType is the type of the key.
   *
   * @generated from field: crypto.KeyType key_type = 1;
   */
  keyType?: KeyType
  /**
   * Data is the data of the key.
   *
   * @generated from field: bytes data = 2;
   */
  data?: Uint8Array
}

// PublicKey contains the message type declaration for PublicKey.
export const PublicKey: MessageType<PublicKey> = createMessageType({
  typeName: 'crypto.PublicKey',
  fields: [
    { no: 1, name: 'key_type', kind: 'enum', T: KeyType_Enum },
    { no: 2, name: 'data', kind: 'scalar', T: ScalarType.BYTES },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
