// Code generated by protoc-gen-srpc. DO NOT EDIT.
// protoc-gen-srpc version: v0.52.1
// source: github.com/s4wave/spacewave/sdk/git/repo.proto

package s4wave_git

import (
	context "context"

	srpc "github.com/aperturerobotics/starpc/srpc"
)

type SRPCGitRepoResourceServiceClient interface {
	// SRPCClient returns the underlying SRPC client.
	SRPCClient() srpc.Client

	ListRefs(ctx context.Context, in *ListRefsRequest) (*ListRefsResponse, error)

	ResolveRef(ctx context.Context, in *ResolveRefRequest) (*ResolveRefResponse, error)

	GetRepoInfo(ctx context.Context, in *GetRepoInfoRequest) (*GetRepoInfoResponse, error)

	GetTreeResource(ctx context.Context, in *GetTreeResourceRequest) (*GetTreeResourceResponse, error)

	GetRepoFilesystemResource(ctx context.Context, in *GetRepoFilesystemResourceRequest) (*GetRepoFilesystemResourceResponse, error)

	Log(ctx context.Context, in *LogRequest) (*LogResponse, error)

	GetCommit(ctx context.Context, in *GetCommitRequest) (*GetCommitResponse, error)

	GetDiffStat(ctx context.Context, in *GetDiffStatRequest) (*GetDiffStatResponse, error)

	GetDiffPatch(ctx context.Context, in *GetDiffPatchRequest) (*GetDiffPatchResponse, error)
}

type srpcGitRepoResourceServiceClient struct {
	cc        srpc.Client
	serviceID string
}

func NewSRPCGitRepoResourceServiceClient(cc srpc.Client) SRPCGitRepoResourceServiceClient {
	return &srpcGitRepoResourceServiceClient{cc: cc, serviceID: SRPCGitRepoResourceServiceServiceID}
}

func NewSRPCGitRepoResourceServiceClientWithServiceID(cc srpc.Client, serviceID string) SRPCGitRepoResourceServiceClient {
	if serviceID == "" {
		serviceID = SRPCGitRepoResourceServiceServiceID
	}
	return &srpcGitRepoResourceServiceClient{cc: cc, serviceID: serviceID}
}

func (c *srpcGitRepoResourceServiceClient) SRPCClient() srpc.Client { return c.cc }

func (c *srpcGitRepoResourceServiceClient) ListRefs(ctx context.Context, in *ListRefsRequest) (*ListRefsResponse, error) {
	out := new(ListRefsResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "ListRefs", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) ResolveRef(ctx context.Context, in *ResolveRefRequest) (*ResolveRefResponse, error) {
	out := new(ResolveRefResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "ResolveRef", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) GetRepoInfo(ctx context.Context, in *GetRepoInfoRequest) (*GetRepoInfoResponse, error) {
	out := new(GetRepoInfoResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "GetRepoInfo", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) GetTreeResource(ctx context.Context, in *GetTreeResourceRequest) (*GetTreeResourceResponse, error) {
	out := new(GetTreeResourceResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "GetTreeResource", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) GetRepoFilesystemResource(ctx context.Context, in *GetRepoFilesystemResourceRequest) (*GetRepoFilesystemResourceResponse, error) {
	out := new(GetRepoFilesystemResourceResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "GetRepoFilesystemResource", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) Log(ctx context.Context, in *LogRequest) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "Log", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) GetCommit(ctx context.Context, in *GetCommitRequest) (*GetCommitResponse, error) {
	out := new(GetCommitResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "GetCommit", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) GetDiffStat(ctx context.Context, in *GetDiffStatRequest) (*GetDiffStatResponse, error) {
	out := new(GetDiffStatResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "GetDiffStat", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srpcGitRepoResourceServiceClient) GetDiffPatch(ctx context.Context, in *GetDiffPatchRequest) (*GetDiffPatchResponse, error) {
	out := new(GetDiffPatchResponse)
	err := c.cc.ExecCall(ctx, c.serviceID, "GetDiffPatch", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type SRPCGitRepoResourceServiceServer interface {
	ListRefs(context.Context, *ListRefsRequest) (*ListRefsResponse, error)

	ResolveRef(context.Context, *ResolveRefRequest) (*ResolveRefResponse, error)

	GetRepoInfo(context.Context, *GetRepoInfoRequest) (*GetRepoInfoResponse, error)

	GetTreeResource(context.Context, *GetTreeResourceRequest) (*GetTreeResourceResponse, error)

	GetRepoFilesystemResource(context.Context, *GetRepoFilesystemResourceRequest) (*GetRepoFilesystemResourceResponse, error)

	Log(context.Context, *LogRequest) (*LogResponse, error)

	GetCommit(context.Context, *GetCommitRequest) (*GetCommitResponse, error)

	GetDiffStat(context.Context, *GetDiffStatRequest) (*GetDiffStatResponse, error)

	GetDiffPatch(context.Context, *GetDiffPatchRequest) (*GetDiffPatchResponse, error)
}

const SRPCGitRepoResourceServiceServiceID = "s4wave.git.GitRepoResourceService"

type SRPCGitRepoResourceServiceHandler struct {
	serviceID string
	impl      SRPCGitRepoResourceServiceServer
}

// NewSRPCGitRepoResourceServiceHandler constructs a new RPC handler.
// serviceID: if empty, uses default: s4wave.git.GitRepoResourceService
func NewSRPCGitRepoResourceServiceHandler(impl SRPCGitRepoResourceServiceServer, serviceID string) srpc.Handler {
	if serviceID == "" {
		serviceID = SRPCGitRepoResourceServiceServiceID
	}
	return &SRPCGitRepoResourceServiceHandler{impl: impl, serviceID: serviceID}
}

// SRPCRegisterGitRepoResourceService registers the implementation with the mux.
// Uses the default serviceID: s4wave.git.GitRepoResourceService
func SRPCRegisterGitRepoResourceService(mux srpc.Mux, impl SRPCGitRepoResourceServiceServer) error {
	return mux.Register(NewSRPCGitRepoResourceServiceHandler(impl, ""))
}

func (d *SRPCGitRepoResourceServiceHandler) GetServiceID() string { return d.serviceID }

func (SRPCGitRepoResourceServiceHandler) GetMethodIDs() []string {
	return []string{
		"ListRefs",
		"ResolveRef",
		"GetRepoInfo",
		"GetTreeResource",
		"GetRepoFilesystemResource",
		"Log",
		"GetCommit",
		"GetDiffStat",
		"GetDiffPatch",
	}
}

func (d *SRPCGitRepoResourceServiceHandler) InvokeMethod(
	serviceID, methodID string,
	strm srpc.Stream,
) (bool, error) {
	if serviceID != "" && serviceID != d.GetServiceID() {
		return false, nil
	}

	switch methodID {
	case "ListRefs":
		return true, d.InvokeMethod_ListRefs(d.impl, strm)
	case "ResolveRef":
		return true, d.InvokeMethod_ResolveRef(d.impl, strm)
	case "GetRepoInfo":
		return true, d.InvokeMethod_GetRepoInfo(d.impl, strm)
	case "GetTreeResource":
		return true, d.InvokeMethod_GetTreeResource(d.impl, strm)
	case "GetRepoFilesystemResource":
		return true, d.InvokeMethod_GetRepoFilesystemResource(d.impl, strm)
	case "Log":
		return true, d.InvokeMethod_Log(d.impl, strm)
	case "GetCommit":
		return true, d.InvokeMethod_GetCommit(d.impl, strm)
	case "GetDiffStat":
		return true, d.InvokeMethod_GetDiffStat(d.impl, strm)
	case "GetDiffPatch":
		return true, d.InvokeMethod_GetDiffPatch(d.impl, strm)
	default:
		return false, nil
	}
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_ListRefs(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(ListRefsRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.ListRefs(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_ResolveRef(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(ResolveRefRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.ResolveRef(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_GetRepoInfo(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(GetRepoInfoRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.GetRepoInfo(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_GetTreeResource(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(GetTreeResourceRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.GetTreeResource(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_GetRepoFilesystemResource(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(GetRepoFilesystemResourceRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.GetRepoFilesystemResource(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_Log(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(LogRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.Log(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_GetCommit(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(GetCommitRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.GetCommit(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_GetDiffStat(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(GetDiffStatRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.GetDiffStat(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

func (SRPCGitRepoResourceServiceHandler) InvokeMethod_GetDiffPatch(impl SRPCGitRepoResourceServiceServer, strm srpc.Stream) error {
	req := new(GetDiffPatchRequest)
	if err := strm.MsgRecv(req); err != nil {
		return err
	}
	out, err := impl.GetDiffPatch(strm.Context(), req)
	if err != nil {
		return err
	}
	return strm.MsgSend(out)
}

type SRPCGitRepoResourceService_ListRefsStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_ListRefsStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_ResolveRefStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_ResolveRefStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_GetRepoInfoStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_GetRepoInfoStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_GetTreeResourceStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_GetTreeResourceStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_GetRepoFilesystemResourceStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_GetRepoFilesystemResourceStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_LogStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_LogStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_GetCommitStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_GetCommitStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_GetDiffStatStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_GetDiffStatStream struct {
	srpc.Stream
}

type SRPCGitRepoResourceService_GetDiffPatchStream interface {
	srpc.Stream
}

type srpcGitRepoResourceService_GetDiffPatchStream struct {
	srpc.Stream
}
