name: Web Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

# Builds images for target boards.
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22']
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ matrix.go }}
    - name: Vendor go
      run: go mod vendor
    - name: Install chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install wasmbrowsertest
      run: go install github.com/agnivade/wasmbrowsertest@53a8815398056ec6dd3aff7e9d1f6c768fe6120d
    - name: Setup wasmexec
      run: mv $(go env GOPATH)/bin/wasmbrowsertest $(go env GOPATH)/bin/go_js_wasm_exec
    - name: Test with wasmbrowsertest
      env:
        GOOS: js
        GOARCH: wasm
      run: go test -tags "webtests" -v ./...
